# Generated by Django 5.2.16 on 2026-07-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_pursuit"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymeasurement",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "남성"), ("female", "여성")],
                max_length=10,
                verbose_name="성별",
            ),
        ),
    ]
