# Generated by Django 5.2.16 on 2026-07-29 00:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_bodymeasurement_gender"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="bodymeasurement",
            table_comment="사용자 신체치수 (성별·키·몸무게 + 상세 둘레, 사용자당 1행. 상세 수치는 추후 사진 추론이 갱신 가능)",
        ),
        migrations.AlterModelTableComment(
            name="bodyphototransaction",
            table_comment="사진 기반 신체치수 측정 트랜잭션 (접수 시 진행중 생성 → 비동기 완료 시 성공/실패)",
        ),
        migrations.AlterModelTableComment(
            name="preferenceoption",
            table_comment="추구미 선호도 옵션 마스터 (11개 카테고리 × N개 옵션)",
        ),
        migrations.AlterModelTableComment(
            name="pursuit",
            table_comment="사용자 추구미 (스타일 선호/기피 선택, 사용자당 1행)",
        ),
        migrations.AlterModelTableComment(
            name="socialaccount",
            table_comment="소셜 로그인 계정 연결 (사용자 1명이 여러 제공사 연결 가능)",
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="서비스 사용자 (소셜 로그인 전용 — password는 사용하지 않음)",
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="arm",
            field=models.DecimalField(
                blank=True,
                db_comment="팔뚝둘레(cm)",
                decimal_places=1,
                help_text="팔뚝둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="팔뚝둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="calf",
            field=models.DecimalField(
                blank=True,
                db_comment="종아리둘레(cm)",
                decimal_places=1,
                help_text="종아리둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="종아리둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="chest",
            field=models.DecimalField(
                blank=True,
                db_comment="가슴둘레(cm)",
                decimal_places=1,
                help_text="가슴둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="가슴둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="행 생성 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "남성"), ("female", "여성")],
                db_comment="성별 (male/female, 미입력 시 빈 문자열)",
                max_length=10,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="height",
            field=models.DecimalField(
                blank=True,
                db_comment="키(cm)",
                decimal_places=1,
                help_text="키(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="키(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="hip",
            field=models.DecimalField(
                blank=True,
                db_comment="엉덩이둘레(cm)",
                decimal_places=1,
                help_text="엉덩이둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="엉덩이둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="shoulder",
            field=models.DecimalField(
                blank=True,
                db_comment="어깨너비(cm)",
                decimal_places=1,
                help_text="어깨너비(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="어깨너비(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="thigh",
            field=models.DecimalField(
                blank=True,
                db_comment="허벅지둘레(cm)",
                decimal_places=1,
                help_text="허벅지둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="허벅지둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="행 수정 시각", verbose_name="수정 시각"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="user",
            field=models.OneToOneField(
                db_comment="대상 사용자 FK (users.id, 사용자당 1행)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_measurement",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="waist",
            field=models.DecimalField(
                blank=True,
                db_comment="허리둘레(cm)",
                decimal_places=1,
                help_text="허리둘레(cm)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="허리둘레(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="weight",
            field=models.DecimalField(
                blank=True,
                db_comment="몸무게(kg)",
                decimal_places=1,
                help_text="몸무게(kg)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="몸무게(kg)",
            ),
        ),
        migrations.AlterField(
            model_name="bodyphototransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="접수 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="bodyphototransaction",
            name="id",
            field=models.UUIDField(
                db_comment="트랜잭션 UUID (외부 노출 식별자)",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bodyphototransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "진행중"),
                    ("succeeded", "성공"),
                    ("failed", "실패"),
                ],
                db_comment="측정 상태 (in_progress/succeeded/failed, 사용자당 진행중 1건)",
                default="in_progress",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="bodyphototransaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="상태 변경 시각", verbose_name="수정 시각"
            ),
        ),
        migrations.AlterField(
            model_name="bodyphototransaction",
            name="user",
            field=models.ForeignKey(
                db_comment="요청 사용자 FK (users.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_photo_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="category",
            field=models.CharField(
                choices=[
                    ("seasons", "계절"),
                    ("styles", "스타일"),
                    ("colors", "색상"),
                    ("necklines", "넥라인"),
                    ("top_fits", "상의핏"),
                    ("top_lengths", "상의기장"),
                    ("sleeves", "소매길이"),
                    ("pants_fits", "팬츠핏"),
                    ("pants_lengths", "팬츠기장"),
                    ("skirt_lengths", "스커트기장"),
                    ("skirt_types", "스커트타입"),
                ],
                db_comment="옵션 카테고리 (seasons/styles/colors 등 11종)",
                max_length=50,
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="code",
            field=models.CharField(
                db_comment="옵션 코드 (카테고리 내 유일, API 페이로드 값)",
                max_length=50,
                verbose_name="옵션 코드",
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="행 생성 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="label",
            field=models.CharField(
                db_comment="화면 표시용 한글 라벨", max_length=50, verbose_name="라벨"
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="meta",
            field=models.JSONField(
                blank=True,
                db_comment='부가 정보 JSON (예: 색상 {"color_hex": "#000000"})',
                default=dict,
                verbose_name="메타데이터",
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="order",
            field=models.PositiveIntegerField(
                db_comment="카테고리 내 표시 순서", default=0, verbose_name="정렬 순서"
            ),
        ),
        migrations.AlterField(
            model_name="preferenceoption",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="행 수정 시각", verbose_name="수정 시각"
            ),
        ),
        migrations.AlterField(
            model_name="pursuit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="행 생성 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="pursuit",
            name="payload",
            field=models.JSONField(
                blank=True,
                db_comment="선호/기피 선택 JSON ({preferred: {카테고리: [코드...]}, avoided: {...}})",
                default=dict,
                verbose_name="선호/기피 데이터",
            ),
        ),
        migrations.AlterField(
            model_name="pursuit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="행 수정 시각", verbose_name="수정 시각"
            ),
        ),
        migrations.AlterField(
            model_name="pursuit",
            name="user",
            field=models.OneToOneField(
                db_comment="대상 사용자 FK (users.id, 사용자당 1행)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pursuit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="connected_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="계정 최초 연결 시각",
                verbose_name="연결 시각",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="email",
            field=models.EmailField(
                blank=True,
                db_comment="제공사 프로필 이메일",
                max_length=254,
                verbose_name="제공사 이메일",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                db_comment="제공사 원본 프로필 JSON (디버깅/추가 필드 대비)",
                default=dict,
                verbose_name="원본 프로필",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="last_login_at",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="이 제공사로 마지막 로그인한 시각",
                verbose_name="마지막 로그인",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("naver", "네이버"),
                    ("kakao", "카카오"),
                    ("google", "구글"),
                    ("apple", "애플"),
                ],
                db_comment="소셜 제공사 (naver/kakao/google/apple)",
                max_length=20,
                verbose_name="제공사",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider_user_id",
            field=models.CharField(
                db_comment="제공사가 발급한 사용자 고유 ID",
                max_length=255,
                verbose_name="제공사 유저 ID",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="user",
            field=models.ForeignKey(
                db_comment="연결된 서비스 사용자 FK (users.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                db_comment="서비스 표시 닉네임 (소셜 프로필에서 초기화)",
                max_length=100,
                verbose_name="닉네임",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(
                blank=True,
                db_comment="프로필 이미지 URL (소셜 프로필에서 초기화)",
                verbose_name="프로필 이미지",
            ),
        ),
        # 자동 생성 id PK는 모델 필드가 아니라 db_comment로 커버되지 않는다 → raw SQL
        migrations.RunSQL(
            sql=[
                "COMMENT ON COLUMN users.id IS '서비스 사용자 PK (자동 증가)';",
                "COMMENT ON COLUMN social_accounts.id IS '소셜 계정 연결 PK (자동 증가)';",
                "COMMENT ON COLUMN body_measurements.id IS '신체치수 PK (자동 증가)';",
                "COMMENT ON COLUMN preference_options.id IS '선호도 옵션 PK (자동 증가)';",
                "COMMENT ON COLUMN pursuits.id IS '추구미 PK (자동 증가)';",
            ],
            reverse_sql=[
                "COMMENT ON COLUMN users.id IS NULL;",
                "COMMENT ON COLUMN social_accounts.id IS NULL;",
                "COMMENT ON COLUMN body_measurements.id IS NULL;",
                "COMMENT ON COLUMN preference_options.id IS NULL;",
                "COMMENT ON COLUMN pursuits.id IS NULL;",
            ],
        ),
    ]
