# Generated by Django 5.2.16 on 2026-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyphototransaction',
            name='error_message',
            field=models.TextField(blank=True, db_comment='측정 실패 사유 (성공/진행중이면 빈 문자열)', default='', verbose_name='실패 사유'),
        ),
    ]
