# Generated by Django 5.2.16 on 2026-08-10 02:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_budget_column_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='neck_length',
            field=models.DecimalField(blank=True, db_comment='목길이(cm)', decimal_places=1, help_text='목길이(cm)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='목길이(cm)'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh_calf_ratio',
            field=models.DecimalField(blank=True, db_comment='허벅지/종아리 비율 (길이 기준)', decimal_places=3, help_text='허벅지/종아리 비율 (길이 기준)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='허벅지/종아리 비율'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='torso_leg_ratio',
            field=models.DecimalField(blank=True, db_comment='상하체 비율 (길이 기준)', decimal_places=3, help_text='상하체 비율 (길이 기준)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='상하체 비율'),
        ),
    ]
