# Generated by Django 5.2.16 on 2026-08-10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_bodymeasurement_table_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurement",
            name="thigh_calf_ratio",
            field=models.DecimalField(
                blank=True,
                db_comment="허벅지/종아리 비율 (길이 기준)",
                decimal_places=3,
                help_text="허벅지/종아리 비율 (길이 기준)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.8")),
                    django.core.validators.MaxValueValidator(Decimal("1.3")),
                ],
                verbose_name="허벅지/종아리 비율",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="torso_leg_ratio",
            field=models.DecimalField(
                blank=True,
                db_comment="상하체 비율 (길이 기준)",
                decimal_places=3,
                help_text="상하체 비율 (길이 기준)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.6")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
                verbose_name="상하체 비율",
            ),
        ),
    ]
