# Generated by Django 5.2.16 on 2026-08-13 06:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_bodymeasurement_length_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='thigh_calf_ratio',
            field=models.DecimalField(blank=True, db_comment='패션용 허벅지 길이감 / 종아리 길이감 비율', decimal_places=3, help_text='패션용 허벅지 길이감 / 종아리 길이감 비율 (SizeKorea 평균 0.823, 참고 분포 약 0.506~1.026)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='허벅지/종아리 길이감 비율'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='torso_leg_ratio',
            field=models.DecimalField(blank=True, db_comment='패션용 상체 길이감 / 하체 길이감 비율', decimal_places=3, help_text='패션용 상체 길이감 / 하체 길이감 비율 (상체=어깨선→골반점, 하체=샅선→발목; SizeKorea 평균 0.660, 참고 분포 약 0.339~0.920)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='상하체 길이감 비율'),
        ),
    ]
