# Generated by Django 5.2.16 on 2026-08-13 12:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_repair_bodymeasurement_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='leg_length',
            field=models.DecimalField(blank=True, db_comment='패션용 하체 길이감(cm, 골반점/위앞엉덩뼈가시→복사뼈/발목)', decimal_places=1, help_text='패션용 하체 길이감(cm, 골반점/위앞엉덩뼈가시→복사뼈/발목)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='패션용 하체 길이감(cm, 골반점/위앞엉덩뼈가시→복사뼈/발목)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='thigh_calf_ratio',
            field=models.DecimalField(blank=True, db_comment='패션용 허벅지 길이감 / 종아리 길이감 비율', decimal_places=3, help_text='패션용 허벅지 길이감 / 종아리 길이감 비율 (정확 3D 랜드마크 SizeKorea 평균 0.823, p01~p99 약 0.652~0.970)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='허벅지/종아리 길이감 비율'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='torso_leg_ratio',
            field=models.DecimalField(blank=True, db_comment='패션용 상체 길이감 / 하체 길이감 비율', decimal_places=3, help_text='패션용 상체 길이감 / 하체 길이감 비율 (상체=어깨선→골반점, 하체=골반점→복사뼈; 정확 3D 랜드마크 SizeKorea 평균 0.546, p01~p99 약 0.466~0.637)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='상하체 길이감 비율'),
        ),
    ]
