# Generated by Django 5.2.16 on 2026-07-24 03:08

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrobeUploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_s3_key",
                    models.CharField(max_length=512, verbose_name="원본 S3 키"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("PROCESSING", "처리중"),
                            ("DONE", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WardrobeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(max_length=512, verbose_name="크롭 이미지 S3 키"),
                ),
                ("item_name", models.CharField(blank=True, default="", max_length=120)),
                ("category_large", models.CharField(max_length=20)),
                (
                    "category_small",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "season",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "style",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=10)),
                ("pattern", models.CharField(blank=True, default="", max_length=10)),
                ("fit", models.CharField(blank=True, default="", max_length=10)),
                ("material", models.CharField(blank=True, default="", max_length=10)),
                ("sleeve", models.CharField(blank=True, default="", max_length=10)),
                ("length", models.CharField(blank=True, default="", max_length=10)),
                (
                    "usage",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("layer_role", models.CharField(blank=True, default="", max_length=10)),
                (
                    "layer_order",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "seg_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="세그멘테이션 메타(raw_label·score·bbox 등)",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="사용자 확정 여부"),
                ),
                (
                    "embedding_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="wardrobe.wardrobeuploadjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wardrobeuploadjob",
            index=models.Index(
                fields=["user", "status"], name="wardrobe_wa_user_id_7aadfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wardrobeitem",
            index=models.Index(
                fields=["user", "category_large"], name="wardrobe_wa_user_id_03e76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wardrobeitem",
            index=models.Index(
                fields=["user", "confirmed"], name="wardrobe_wa_user_id_93e7e7_idx"
            ),
        ),
    ]
