# Generated by Django 5.2.16 on 2026-07-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="wardrobeitem",
            new_name="wardrobe_it_user_id_c33cda_idx",
            old_name="wardrobe_wa_user_id_03e76a_idx",
        ),
        migrations.RenameIndex(
            model_name="wardrobeitem",
            new_name="wardrobe_it_user_id_b78819_idx",
            old_name="wardrobe_wa_user_id_93e7e7_idx",
        ),
        migrations.RenameIndex(
            model_name="wardrobeuploadjob",
            new_name="wardrobe_up_user_id_8ec4a6_idx",
            old_name="wardrobe_wa_user_id_7aadfa_idx",
        ),
        migrations.AlterModelTable(
            name="wardrobeitem",
            table="wardrobe_item",
        ),
        migrations.AlterModelTable(
            name="wardrobeuploadjob",
            table="wardrobe_upload_job",
        ),
    ]
