# Generated by Django 5.2.16 on 2026-07-29 00:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0002_set_table_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="wardrobeitem",
            table_comment="사용자 옷장 아이템 (업로드 사진에서 분리·태깅된 옷 1벌, 벡터는 Qdrant에 별도 저장)",
        ),
        migrations.AlterModelTableComment(
            name="wardrobeuploadjob",
            table_comment="옷장 사진 업로드 처리 job (이미지 프로세서 콜백 멱등성 기준)",
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="category_large",
            field=models.CharField(
                db_comment="대분류 (상의/하의/아우터/신발/가방 등)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="category_small",
            field=models.CharField(
                blank=True,
                db_comment="소분류 (티셔츠/청바지 등)",
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="color",
            field=models.CharField(
                blank=True, db_comment="색상 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="confirmed",
            field=models.BooleanField(
                db_comment="사용자 확정 여부 (false: 확인 대기 — 추천 검색 제외)",
                default=False,
                verbose_name="사용자 확정 여부",
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_comment="행 생성 시각"),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="embedding_version",
            field=models.CharField(
                blank=True,
                db_comment="Qdrant 임베딩 버전 (재임베딩 판단 기준)",
                default="",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="fit",
            field=models.CharField(
                blank=True, db_comment="핏 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="id",
            field=models.UUIDField(
                db_comment="아이템 UUID (외부 노출 식별자)",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="item_name",
            field=models.CharField(
                blank=True,
                db_comment="아이템 표시 이름 (태깅 생성 또는 사용자 수정)",
                default="",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="job",
            field=models.ForeignKey(
                db_comment="생성 출처 업로드 job FK (wardrobe_upload_job.id, job 삭제 시 NULL)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="wardrobe.wardrobeuploadjob",
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="layer_order",
            field=models.PositiveSmallIntegerField(
                blank=True, db_comment="레이어링 착용 순서 (안쪽부터 1)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="layer_role",
            field=models.CharField(
                blank=True, db_comment="레이어링 역할 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="length",
            field=models.CharField(
                blank=True, db_comment="기장 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="material",
            field=models.CharField(
                blank=True, db_comment="소재 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="pattern",
            field=models.CharField(
                blank=True, db_comment="패턴 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="s3_key",
            field=models.CharField(
                db_comment="배경 제거·크롭된 아이템 이미지 S3 키",
                max_length=512,
                verbose_name="크롭 이미지 S3 키",
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="season",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                db_comment="계절 태그 배열",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="seg_meta",
            field=models.JSONField(
                blank=True,
                db_comment="세그멘테이션 메타 JSON (raw_label/score/bbox 등)",
                default=dict,
                verbose_name="세그멘테이션 메타(raw_label·score·bbox 등)",
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="sleeve",
            field=models.CharField(
                blank=True, db_comment="소매 길이 태그", default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="style",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                db_comment="스타일 태그 배열",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_comment="행 수정 시각"),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="usage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                db_comment="용도(TPO) 태그 배열",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="user",
            field=models.ForeignKey(
                db_comment="소유 사용자 FK (users.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wardrobe_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="job 생성(접수) 시각"
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="error_message",
            field=models.TextField(
                blank=True, db_comment="실패 시 오류 메시지", default=""
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, db_comment="처리 종료 시각 (DONE/FAILED 전환 시)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="id",
            field=models.UUIDField(
                db_comment="job UUID (외부 노출 식별자)",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="source_s3_key",
            field=models.CharField(
                db_comment="업로드 원본 이미지 S3 키",
                max_length=512,
                verbose_name="원본 S3 키",
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기"),
                    ("PROCESSING", "처리중"),
                    ("DONE", "완료"),
                    ("FAILED", "실패"),
                ],
                db_comment="처리 상태 (PENDING/PROCESSING/DONE/FAILED)",
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="wardrobeuploadjob",
            name="user",
            field=models.ForeignKey(
                db_comment="업로드 사용자 FK (users.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wardrobe_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
