# Generated by Django 5.2.16 on 2026-08-10 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_table_column_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWardrobeRoom',
            fields=[
                ('id', models.UUIDField(db_comment='공유방 UUID (외부 노출 식별자)', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_comment='공유방 이름 (예: 가족 옷장)', max_length=100, verbose_name='방 이름')),
                ('invite_code', models.CharField(blank=True, db_comment='6자리 초대용 핀코드', max_length=6, null=True, unique=True, verbose_name='초대코드')),
                ('code_expires_at', models.DateTimeField(blank=True, db_comment='초대코드 유효 만료 시각', null=True, verbose_name='초대코드 만료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='방 개설 시각', verbose_name='생성일시')),
            ],
            options={
                'db_table': 'shared_wardrobe_room',
                'db_table_comment': '공유 옷장 그룹 방',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedWardrobeItem',
            fields=[
                ('id', models.UUIDField(db_comment='공유 아이템 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', '공유가능'), ('borrowed', '대여중'), ('private', '나만보기')], db_comment='공유 대여 가능 상태', default='available', max_length=15, verbose_name='공유상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='공유방 등록 시각', verbose_name='등록일시')),
                ('registered_by', models.ForeignKey(blank=True, db_comment='등록 사용자 FK (사용자 탈퇴 시에도 옷 유지를 위해 SET_NULL 지원)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_items', to=settings.AUTH_USER_MODEL)),
                ('wardrobe_item', models.ForeignKey(db_comment='원본 옷장 아이템 FK', on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances', to='wardrobe.wardrobeitem')),
                ('room', models.ForeignKey(db_comment='소속 공유방 FK', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.sharedwardroberoom')),
            ],
            options={
                'db_table': 'shared_wardrobe_item',
                'db_table_comment': '공유 옷장 내 등록된 의류 아이템',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedWardrobeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '방장'), ('member', '멤버')], db_comment='방 권한 (owner/member)', default='member', max_length=10, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_comment='방 참가 시각', verbose_name='참여일시')),
                ('user', models.ForeignKey(db_comment='참여 사용자 FK', on_delete=django.db.models.deletion.CASCADE, related_name='shared_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(db_comment='소속 공유방 FK', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wardrobe.sharedwardroberoom')),
            ],
            options={
                'db_table': 'shared_wardrobe_member',
                'db_table_comment': '공유 옷장 그룹 참여자',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
