# Generated by Django 5.2.17 on 2026-08-13 04:59

from django.conf import settings
from django.db import migrations, models


def backfill_added_to_closet_at(apps, schema_editor):
    """이미 있는 아이템은 전부 '옷장에 든 것'으로 본다.

    이 필드가 생기기 전에는 옷장 목록이 아이템을 가리지 않았다. 그러니 지금 옷장에
    보이던 옷은 앞으로도 보여야 한다 — NULL 로 두면 사용자 눈에는 옷장이 통째로
    비어 버린다. 생성 시각을 그대로 편입 시각으로 삼는다.
    """
    WardrobeItem = apps.get_model("wardrobe", "WardrobeItem")
    WardrobeItem.objects.filter(added_to_closet_at__isnull=True).update(
        added_to_closet_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_upload_job_input_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='added_to_closet_at',
            field=models.DateTimeField(blank=True, db_comment='사용자가 이 옷을 옷장에 두기로 한 시각 (NULL: 룩 사진에서 뽑혔지만 아직 옷장에 넣지 않음 — 옷장 목록에서 제외)', null=True, verbose_name='옷장 편입 시각'),
        ),
        migrations.RunPython(
            backfill_added_to_closet_at,
            # 되돌릴 때는 값만 비우면 된다 — 필드 자체는 AddField 가 되돌린다.
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'added_to_closet_at'], name='wardrobe_it_user_id_f64141_idx'),
        ),
    ]
