# Generated by Django 5.2.17 on 2026-08-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0009_shared_wardrobe_item_unique_room_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='pending_share_room',
            field=models.ForeignKey(blank=True, db_comment='확정 시 공유할 예약 방 FK (NULL: 예약 없음, 방 삭제 시 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_items', to='wardrobe.sharedwardroberoom'),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='pending_share_status',
            field=models.CharField(blank=True, db_comment='예약 소진 시 적용할 공유 상태 (available/borrowed/private, 빈 문자열: 기본값 사용)', default='', max_length=15, verbose_name='공유 예약 상태'),
        ),
        migrations.AddField(
            model_name='wardrobeuploadjob',
            name='shared_room',
            field=models.ForeignKey(blank=True, db_comment='등록 시 지정한 공유 예약 방 FK (NULL: 공유 안 함, 방 삭제 시 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_jobs', to='wardrobe.sharedwardroberoom'),
        ),
        migrations.AddField(
            model_name='wardrobeuploadjob',
            name='shared_status',
            field=models.CharField(blank=True, db_comment='공유 예약 시 적용할 상태 (available/borrowed/private, 빈 문자열: 예약 없음)', default='', max_length=15, verbose_name='공유 예약 상태'),
        ),
    ]
