# Generated by Django 5.2.16 on 2026-08-18 07:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wardrobe", "0010_pending_share_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # users.0002에서 실제 사용자 테이블명이 users_user에서 users로 바뀐다.
        # 이 상태를 의존해야 신규 FK SQL도 현재 테이블명을 정확히 참조한다.
        ("users", "0002_rename_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrobeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="개인 옷장 사용자 카테고리 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="사용자에게 표시할 개인 옷장 카테고리명",
                        max_length=30,
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        db_comment=(
                            "중복 검사용 정규화 카테고리명 "
                            "(공백 정리 및 대소문자 통합)"
                        ),
                        editable=False,
                        max_length=30,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_comment="사용자 카테고리 표시 순서 (0부터 오름차순)",
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="카테고리 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="카테고리 수정 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="카테고리 소유 사용자 FK (users.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wardrobe_category",
                "db_table_comment": "개인 옷장의 사용자 정의 정리 카테고리",
                "ordering": ["position", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WardrobeItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="개인 옷장 아이템 카테고리 연결 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="아이템 카테고리 연결 시각"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_comment="아이템에 지정한 사용자 카테고리 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_links",
                        to="wardrobe.wardrobecategory",
                    ),
                ),
                (
                    "wardrobe_item",
                    models.ForeignKey(
                        db_comment="분류할 개인 옷장 아이템 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_category_links",
                        to="wardrobe.wardrobeitem",
                    ),
                ),
            ],
            options={
                "db_table": "wardrobe_item_category",
                "db_table_comment": "개인 옷장 아이템과 사용자 카테고리 연결",
            },
        ),
        migrations.AddField(
            model_name="wardrobeitem",
            name="custom_categories",
            field=models.ManyToManyField(
                related_name="wardrobe_items",
                through="wardrobe.WardrobeItemCategory",
                to="wardrobe.wardrobecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="wardrobecategory",
            index=models.Index(fields=["user", "position"], name="idx_wd_cat_user_pos"),
        ),
        migrations.AddConstraint(
            model_name="wardrobecategory",
            constraint=models.UniqueConstraint(
                fields=("user", "normalized_name"),
                name="uq_wardrobe_category_user_normalized_name",
            ),
        ),
        migrations.AddIndex(
            model_name="wardrobeitemcategory",
            index=models.Index(
                fields=["category", "wardrobe_item"], name="idx_wd_item_cat_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="wardrobeitemcategory",
            constraint=models.UniqueConstraint(
                fields=("wardrobe_item", "category"),
                name="uq_wardrobe_item_category_pair",
            ),
        ),
    ]
