# Generated by Django 5.2.17 on 2026-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0010_pending_share_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='is_favorite',
            field=models.BooleanField(db_comment='사용자가 별로 표시한 옷 (자주 입는 옷 모아보기용)', default=False, verbose_name='즐겨찾기'),
        ),
    ]
