# Generated by Django 5.2.16 on 2026-08-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_merge_duplicate_0024_leaves'),
        ('wardrobe', '0012_personal_wardrobe_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeViewPreference',
            fields=[
                ('user', models.OneToOneField(db_comment='옷장 보기 설정 소유 사용자 FK (users.id, 사용자당 1건)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wardrobe_view_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('group_mode', models.CharField(choices=[('SYSTEM_CATEGORY', '기본 카테고리별'), ('HASHTAG', '해시태그별')], db_comment='옷장 섹션 묶기 방식 (SYSTEM_CATEGORY/HASHTAG)', default='SYSTEM_CATEGORY', max_length=20)),
                ('item_sort', models.CharField(choices=[('ADDED_DESC', '최근 추가순'), ('COLOR_NAME_ASC', '색상·이름순')], db_comment='섹션 내부 아이템 정렬 방식 (ADDED_DESC/COLOR_NAME_ASC)', default='ADDED_DESC', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='옷장 보기 설정 수정 시각')),
            ],
            options={
                'db_table': 'wardrobe_view_preference',
                'db_table_comment': '사용자별 개인 옷장 묶기 및 아이템 정렬 설정',
            },
        ),
    ]
