# Generated by Django 5.2.16 on 2026-07-29 00:59

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_navertaggingbatch"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="naverproduct",
            table_comment="네이버 쇼핑 수집 상품 카탈로그 (collector/naver가 upsert, 추천 후보 원천)",
        ),
        migrations.AlterModelTableComment(
            name="naverproductsize",
            table_comment="상품 사이즈별 실측 치수 (naver_product 하위 종속, 사이즈 적합성 판단용)",
        ),
        migrations.AlterModelTableComment(
            name="navertaggingbatch",
            table_comment="OpenAI Batch API 상품 태깅 작업 추적 (collector/naver batch_tagger가 기록)",
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="brand",
            field=models.CharField(
                blank=True, db_comment="브랜드명", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="category_large",
            field=models.CharField(
                db_comment="서비스 대분류 (컨플루언스 태그 체계: 상의/하의/아우터/신발/가방/모자/액세서리 등)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="category_small",
            field=models.CharField(
                db_comment="서비스 소분류 (컨플루언스 태그 체계: 티셔츠/청바지 등)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="category_source",
            field=models.CharField(
                db_comment="분류 출처 (keyword: 검색 키워드 규칙 / llm: LLM 태깅)",
                db_default="keyword",
                default="keyword",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집(크롤링) 시각"),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="color",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="색상 태그 배열 (블랙/화이트 등)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="fit",
            field=models.CharField(
                blank=True,
                db_comment="핏 태그 (오버사이즈/슬림/와이드 등)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="hprice",
            field=models.IntegerField(
                blank=True, db_comment="최고가 (원, 대부분 미제공)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="image_url",
            field=models.TextField(
                blank=True, db_comment="상품 대표 이미지 URL (네이버 CDN)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="layer_order",
            field=models.SmallIntegerField(
                blank=True, db_comment="레이어링 착용 순서 (안쪽부터 1)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="layer_role",
            field=models.CharField(
                blank=True,
                db_comment="레이어링 역할 (이너/미드/아우터 등)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="length",
            field=models.CharField(
                blank=True,
                db_comment="기장 태그 (크롭/롱/미디 등)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="link",
            field=models.TextField(
                blank=True, db_comment="상품 상세 페이지 URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="lprice",
            field=models.IntegerField(blank=True, db_comment="최저가 (원)", null=True),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="maker",
            field=models.CharField(
                blank=True, db_comment="제조사명", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="mall_name",
            field=models.CharField(
                blank=True, db_comment="판매 쇼핑몰 이름", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="material",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="소재 태그 배열 (면/데님/니트 등)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="naver_category1",
            field=models.CharField(
                blank=True,
                db_comment="네이버 카테고리 대분류 (category1)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="naver_category2",
            field=models.CharField(
                blank=True,
                db_comment="네이버 카테고리 중분류 (category2)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="naver_category3",
            field=models.CharField(
                blank=True,
                db_comment="네이버 카테고리 소분류 (category3)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="naver_category4",
            field=models.CharField(
                blank=True,
                db_comment="네이버 카테고리 세분류 (category4)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="naver_product_id",
            field=models.CharField(
                db_comment="네이버 상품 고유 ID (productId)", max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="pattern",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="패턴 태그 배열 (무지/스트라이프/체크 등)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="product_type",
            field=models.SmallIntegerField(
                blank=True,
                db_comment="네이버 productType 코드 (1~12: 일반/중고/단종/판매예정 × 상품구분)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                db_comment="네이버 API 원본 응답 JSON (디버깅/재처리용)",
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="search_keyword",
            field=models.CharField(
                blank=True,
                db_comment="수집에 사용한 네이버 검색 키워드",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="season",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="계절 태그 배열 (봄/여름/가을/겨울)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="sleeve",
            field=models.CharField(
                blank=True,
                db_comment="소매 길이 태그 (긴팔/반팔/민소매 등)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="style",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="스타일 태그 배열 (캐주얼/미니멀/스트릿 등)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="tag_source",
            field=models.JSONField(
                blank=True,
                db_comment="태그별 출처 기록 JSON ({태그명: keyword|llm})",
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="tagged_at",
            field=models.DateTimeField(
                blank=True, db_comment="태깅 완료 시각", null=True
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="tagging_model",
            field=models.CharField(
                blank=True,
                db_comment="태깅에 사용한 LLM 모델명",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="tagging_status",
            field=models.CharField(
                db_comment="LLM 태깅 상태 (pending → queued → tagged | failed)",
                db_default="pending",
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="tagging_used_image",
            field=models.BooleanField(
                db_comment="태깅 시 상품 이미지 입력 사용 여부",
                db_default=False,
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="title",
            field=models.CharField(
                db_comment="상품명 (HTML 태그 제거 후)", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="title_raw",
            field=models.CharField(
                blank=True,
                db_comment="상품명 원본 (네이버 응답 그대로, <b> 태그 포함)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="naverproduct",
            name="usage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_comment="용도(TPO) 태그 배열 (데일리/출근/운동 등)",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="chest_width",
            field=models.DecimalField(
                blank=True,
                db_comment="가슴단면 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="extra_measurements",
            field=models.JSONField(
                blank=True,
                db_comment="기타 측정값 JSON (표준 컬럼 외 항목)",
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="foot_length_mm",
            field=models.DecimalField(
                blank=True,
                db_comment="발길이 (mm, 신발 전용)",
                decimal_places=1,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="hem_width",
            field=models.DecimalField(
                blank=True,
                db_comment="밑단단면 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="hip_width",
            field=models.DecimalField(
                blank=True,
                db_comment="엉덩이단면 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="product",
            field=models.ForeignKey(
                db_comment="대상 상품 FK (naver_product.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="catalog.naverproduct",
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="rise",
            field=models.DecimalField(
                blank=True,
                db_comment="밑위 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="shoulder_width",
            field=models.DecimalField(
                blank=True,
                db_comment="어깨너비 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="size_label",
            field=models.CharField(
                db_comment="사이즈 표기 (S/M/L, 90~110, 230~290, FREE 등)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="size_system",
            field=models.CharField(
                blank=True,
                db_comment="사이즈 체계 (KR/US/EU/UK)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="sleeve_length",
            field=models.DecimalField(
                blank=True,
                db_comment="소매길이 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="source",
            field=models.CharField(
                db_comment="치수 출처 (manual: 수동 입력 / crawl: 별도 수집)",
                db_default="manual",
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="thigh_width",
            field=models.DecimalField(
                blank=True,
                db_comment="허벅지단면 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="total_length",
            field=models.DecimalField(
                blank=True,
                db_comment="총장 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="naverproductsize",
            name="waist_width",
            field=models.DecimalField(
                blank=True,
                db_comment="허리단면 (cm)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="batch_id",
            field=models.CharField(
                db_comment="OpenAI Batch API 배치 ID", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, db_comment="배치 완료 시각", null=True
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="error",
            field=models.TextField(
                blank=True, db_comment="배치 실패 시 오류 내용", null=True
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="error_file_id",
            field=models.CharField(
                blank=True, db_comment="OpenAI 오류 파일 ID", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="include_image",
            field=models.BooleanField(
                db_comment="요청에 상품 이미지 포함 여부",
                db_default=False,
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="input_file_id",
            field=models.CharField(
                blank=True, db_comment="OpenAI 입력 파일 ID", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="model",
            field=models.CharField(
                blank=True,
                db_comment="배치에 사용한 LLM 모델명",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="output_file_id",
            field=models.CharField(
                blank=True,
                db_comment="OpenAI 출력(결과) 파일 ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="request_count",
            field=models.IntegerField(
                db_comment="배치에 포함된 태깅 요청(상품) 수", db_default=0, default=0
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="status",
            field=models.CharField(
                db_comment="배치 상태 (submitted/validating/in_progress/finalizing/completed/failed/expired/cancelled)",
                db_default="submitted",
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="navertaggingbatch",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        # 자동 생성 id PK는 모델 필드가 아니라 db_comment로 커버되지 않는다 → raw SQL
        migrations.RunSQL(
            sql=[
                "COMMENT ON COLUMN naver_product.id IS '네이버 상품 PK (자동 증가)';",
                "COMMENT ON COLUMN naver_tagging_batch.id IS '태깅 배치 PK (자동 증가)';",
                "COMMENT ON COLUMN naver_product_size.id IS '상품 사이즈 PK (자동 증가)';",
            ],
            reverse_sql=[
                "COMMENT ON COLUMN naver_product.id IS NULL;",
                "COMMENT ON COLUMN naver_tagging_batch.id IS NULL;",
                "COMMENT ON COLUMN naver_product_size.id IS NULL;",
            ],
        ),
    ]
