# Generated by Django 5.2.16 on 2026-08-06 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # 골든셋 테이블은 전부 goldenset 스키마에 만든다 (models.GOLDENSET_SCHEMA).
        # Django에 스키마 생성 연산이 없어 원시 SQL로 선행 생성한다.
        # 마이그레이션 사용자에게 CREATE 권한이 필요하다.
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS goldenset;',
            # RESTRICT라 스키마에 객체가 남아 있으면 실패한다 — 되돌리기가
            # 실수로 데이터를 지우지 않게 하는 안전장치다.
            reverse_sql='DROP SCHEMA IF EXISTS goldenset RESTRICT;',
        ),
        migrations.CreateModel(
            name='GoldenDataset',
            fields=[
                ('id', models.UUIDField(db_comment='골든셋 버전 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='골든셋 표시 이름', max_length=120)),
                ('version', models.CharField(db_comment='골든셋 버전 식별자', max_length=40)),
                ('status', models.CharField(choices=[('PILOT', '파일럿'), ('DRAFT', '초안'), ('ACTIVE', '운영'), ('ARCHIVED', '보관')], db_comment='골든셋 상태 (PILOT/DRAFT/ACTIVE/ARCHIVED)', default='PILOT', max_length=16)),
                ('run_id', models.CharField(blank=True, db_comment='오프라인 파이프라인 실행 식별자', default='', max_length=80)),
                ('source_metadata', models.JSONField(blank=True, db_comment='출처·분할·분포 등 데이터셋 메타데이터 JSON', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='골든셋 버전 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='골든셋 버전 수정 시각')),
            ],
            options={
                'db_table': 'goldenset"."golden_dataset',
                'db_table_comment': '패션 판단 지식 구축에 사용하는 골든셋 버전',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uq_golden_dataset_name_version')],
            },
        ),
        migrations.CreateModel(
            name='GoldenImage',
            fields=[
                ('id', models.UUIDField(db_comment='골든 이미지 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('golden_id', models.CharField(db_comment='manifest에서 사용하는 안정적인 이미지 식별자', max_length=80)),
                ('source_uri', models.CharField(db_comment='원본 이미지 S3 URI 또는 파일럿 입력 경로', max_length=1024)),
                ('source_name', models.CharField(blank=True, db_comment='이미지 출처 이름', default='', max_length=160)),
                ('usage_scope', models.CharField(choices=[('INTERNAL', '내부 분석'), ('EVALUATION', '평가 전용'), ('UNKNOWN', '미확인')], db_comment='이미지 활용 범위 (INTERNAL/EVALUATION/UNKNOWN)', default='UNKNOWN', max_length=16)),
                ('original_exposable', models.BooleanField(db_comment='원본 이미지를 사용자 응답에 노출할 수 있는지 여부', default=False)),
                ('image_sha256', models.CharField(db_comment='원본 이미지 SHA-256 해시', max_length=64)),
                ('perceptual_hash', models.CharField(blank=True, db_comment='근접 중복 탐지용 지각 해시', default='', max_length=32)),
                ('split', models.CharField(choices=[('KNOWLEDGE', '지식 발견'), ('VALIDATION', '검증'), ('TEST', '비공개 테스트')], db_comment='데이터 분할 (KNOWLEDGE/VALIDATION/TEST)', default='KNOWLEDGE', max_length=16)),
                ('presentation_group', models.CharField(blank=True, db_comment='수집·공정성 평가용 성별 표현 그룹', default='', max_length=40)),
                ('cluster_id', models.CharField(blank=True, db_comment='임베딩 클러스터 식별자', default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, db_comment='스타일·계절·TPO·선정 이유 등 이미지 메타데이터 JSON', default=dict)),
                ('human_score', models.FloatField(blank=True, db_comment='쌍대 비교에서 환산한 상대 점수 (0~100)', null=True)),
                ('score_band', models.CharField(blank=True, choices=[('high', '상'), ('mid', '중'), ('low', '하'), ('', '미정')], db_comment='보조 점수 앵커 구간 (high/mid/low, 미정은 빈 문자열)', default='', max_length=4)),
                ('score_confidence', models.FloatField(blank=True, db_comment='사람 점수 신뢰도 (0~1)', null=True)),
                ('embedding_version', models.CharField(blank=True, db_comment='이미지 임베딩 모델·전처리 버전', default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='골든 이미지 등록 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='골든 이미지 수정 시각')),
                ('dataset', models.ForeignKey(db_comment='소속 골든셋 버전 FK (golden_dataset.id)', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goldenset.goldendataset')),
            ],
            options={
                'db_table': 'goldenset"."golden_image',
                'db_table_comment': '골든셋 원본 이미지와 보조 점수 앵커 메타데이터',
                'ordering': ['golden_id'],
            },
        ),
        migrations.CreateModel(
            name='GoldenAnalysis',
            fields=[
                ('id', models.UUIDField(db_comment='골든 이미지 분석 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(db_comment='분석에 사용한 멀티모달 모델 버전', max_length=120)),
                ('prompt_version', models.CharField(db_comment='분석 프롬프트 버전', max_length=80)),
                ('schema_version', models.CharField(db_comment='구조화 분석 스키마 버전', max_length=40)),
                ('status', models.CharField(choices=[('SUCCEEDED', '성공'), ('FAILED', '실패')], db_comment='분석 상태 (SUCCEEDED/FAILED)', default='SUCCEEDED', max_length=16)),
                ('result', models.JSONField(blank=True, db_comment='관찰·영역·관계·판단·불확실성 구조화 결과 JSON', default=dict)),
                ('error_message', models.TextField(blank=True, db_comment='분석 실패 사유', default='')),
                ('latency_seconds', models.FloatField(blank=True, db_comment='멀티모달 분석 응답 시간(초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='분석 실행 시각')),
                ('image', models.ForeignKey(db_comment='분석 대상 골든 이미지 FK (golden_image.id)', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='goldenset.goldenimage')),
            ],
            options={
                'db_table': 'goldenset"."golden_analysis',
                'db_table_comment': '모델·프롬프트 버전별 골든 이미지 구조화 분석',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldenPrinciple',
            fields=[
                ('id', models.UUIDField(db_comment='조건부 패션 원칙 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principle_key', models.CharField(db_comment='실행 내에서 안정적인 원칙 식별자', max_length=120)),
                ('dimension', models.CharField(db_comment='판단 차원 (color/silhouette/proportion 등)', max_length=40)),
                ('statement', models.TextField(db_comment='검수 대상 조건부 패션 원칙 문장')),
                ('applies_when', models.JSONField(blank=True, db_comment='원칙 적용 조건 문자열 배열', default=list)),
                ('exceptions', models.JSONField(blank=True, db_comment='원칙 예외·적용 제외 조건 문자열 배열', default=list)),
                ('confidence', models.FloatField(db_comment='근거 수·검수 합의도를 반영한 원칙 신뢰도 (0~1)', default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('APPROVED', '승인'), ('REJECTED', '기각'), ('RETIRED', '폐기')], db_comment='원칙 상태 (DRAFT/APPROVED/REJECTED/RETIRED)', default='DRAFT', max_length=16)),
                ('version', models.CharField(db_comment='원칙 생성 스키마·프롬프트 버전', max_length=40)),
                ('metadata', models.JSONField(blank=True, db_comment='클러스터·생성 모델·검수 통계 등 원칙 메타데이터 JSON', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='원칙 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='원칙 수정 시각')),
                ('dataset', models.ForeignKey(db_comment='원칙을 생성한 골든셋 버전 FK (golden_dataset.id)', on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='goldenset.goldendataset')),
            ],
            options={
                'db_table': 'goldenset"."golden_principle',
                'db_table_comment': '골든 이미지 근거에서 추출한 조건부 패션 판단 원칙',
                'ordering': ['dimension', 'principle_key'],
            },
        ),
        migrations.CreateModel(
            name='GoldenPrincipleEvidence',
            fields=[
                ('id', models.BigAutoField(db_comment='원칙 근거 행 PK', primary_key=True, serialize=False)),
                ('claim_key', models.CharField(db_comment='분석 결과 내부 claim 식별자', max_length=120)),
                ('region_ids', models.JSONField(blank=True, db_comment='claim이 참조하는 이미지 영역 식별자 배열', default=list)),
                ('polarity', models.CharField(choices=[('SUPPORT', '지지'), ('EXCEPTION', '예외'), ('COUNTEREXAMPLE', '반례')], db_comment='근거 관계 (SUPPORT/EXCEPTION/COUNTEREXAMPLE)', default='SUPPORT', max_length=16)),
                ('confidence', models.FloatField(db_comment='해당 이미지 근거 연결 신뢰도 (0~1)', default=0.0)),
                ('image', models.ForeignKey(db_comment='근거 골든 이미지 FK (golden_image.id)', on_delete=django.db.models.deletion.CASCADE, related_name='principle_evidence_links', to='goldenset.goldenimage')),
                ('principle', models.ForeignKey(db_comment='조건부 패션 원칙 FK (golden_principle.id)', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='goldenset.goldenprinciple')),
            ],
            options={
                'db_table': 'goldenset"."golden_principle_evidence',
                'db_table_comment': '조건부 패션 원칙과 이미지 영역 claim의 연결',
            },
        ),
        migrations.CreateModel(
            name='GoldenReview',
            fields=[
                ('id', models.BigAutoField(db_comment='사람 검수 행 PK', primary_key=True, serialize=False)),
                ('review_key', models.CharField(db_comment='검수 파일 재수입을 위한 안정적인 검수 행 식별자', max_length=255)),
                ('reviewer_label', models.CharField(db_comment='개인정보 대신 사용하는 검수자 별칭', max_length=80)),
                ('verdict', models.CharField(choices=[('APPROVE', '승인'), ('EDIT', '수정 필요'), ('REJECT', '기각'), ('UNSURE', '판단 보류')], db_comment='검수 판정 (APPROVE/EDIT/REJECT/UNSURE)', max_length=16)),
                ('scores', models.JSONField(blank=True, db_comment='축별 점수·종합점수·확신도 등 사람 평가 JSON', default=dict)),
                ('rationale', models.TextField(blank=True, db_comment='검수 사유와 수정 제안', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='검수 시각')),
                ('dataset', models.ForeignKey(db_comment='검수 대상 골든셋 버전 FK (golden_dataset.id)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goldenset.goldendataset')),
                ('image', models.ForeignKey(blank=True, db_comment='이미지 분석 검수 대상 FK (없으면 null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goldenset.goldenimage')),
                ('principle', models.ForeignKey(blank=True, db_comment='패션 원칙 검수 대상 FK (없으면 null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goldenset.goldenprinciple')),
            ],
            options={
                'db_table': 'goldenset"."golden_review',
                'db_table_comment': '골든 이미지 분석·패션 원칙에 대한 사람 검수',
            },
        ),
        migrations.AddIndex(
            model_name='goldenimage',
            index=models.Index(fields=['dataset', 'split'], name='golden_imag_dataset_f4f869_idx'),
        ),
        migrations.AddIndex(
            model_name='goldenimage',
            index=models.Index(fields=['dataset', 'score_band'], name='golden_imag_dataset_46bb21_idx'),
        ),
        migrations.AddIndex(
            model_name='goldenimage',
            index=models.Index(fields=['image_sha256'], name='golden_imag_image_s_df0d26_idx'),
        ),
        migrations.AddConstraint(
            model_name='goldenimage',
            constraint=models.UniqueConstraint(fields=('dataset', 'golden_id'), name='uq_golden_image_dataset_golden_id'),
        ),
        migrations.AddConstraint(
            model_name='goldenanalysis',
            constraint=models.UniqueConstraint(fields=('image', 'model_version', 'prompt_version', 'schema_version'), name='uq_golden_analysis_versions'),
        ),
        migrations.AddIndex(
            model_name='goldenprinciple',
            index=models.Index(fields=['dataset', 'status'], name='golden_prin_dataset_922463_idx'),
        ),
        migrations.AddIndex(
            model_name='goldenprinciple',
            index=models.Index(fields=['dimension', 'status'], name='golden_prin_dimensi_38dcec_idx'),
        ),
        migrations.AddConstraint(
            model_name='goldenprinciple',
            constraint=models.UniqueConstraint(fields=('dataset', 'principle_key', 'version'), name='uq_golden_principle_version'),
        ),
        migrations.AddConstraint(
            model_name='goldenprincipleevidence',
            constraint=models.UniqueConstraint(fields=('principle', 'image', 'claim_key', 'polarity'), name='uq_golden_principle_evidence'),
        ),
        migrations.AddIndex(
            model_name='goldenreview',
            index=models.Index(fields=['dataset', 'reviewer_label'], name='golden_revi_dataset_768fe2_idx'),
        ),
        migrations.AddConstraint(
            model_name='goldenreview',
            constraint=models.UniqueConstraint(fields=('dataset', 'review_key'), name='uq_golden_review_key'),
        ),
        migrations.AddConstraint(
            model_name='goldenreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('principle__isnull', True)), models.Q(('image__isnull', True), ('principle__isnull', False)), _connector='OR'), name='ck_golden_review_exactly_one_target'),
        ),
    ]
