# Generated by Django 5.2.16 on 2026-08-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenprinciple',
            name='applies_when',
            field=models.JSONField(blank=True, db_comment='스타일·추구미·계절·TPO·의류 조건별 원칙 적용 조건 JSON', default=dict),
        ),
        migrations.CreateModel(
            name='GoldenPairwiseReview',
            fields=[
                ('id', models.BigAutoField(db_comment='골든 쌍대 비교 검수 행 PK', primary_key=True, serialize=False)),
                ('pair_key', models.CharField(db_comment='실행 내에서 안정적인 비교 쌍 식별자', max_length=120)),
                ('reviewer_label', models.CharField(db_comment='개인정보 대신 사용하는 검수자 별칭', max_length=80)),
                ('comparison_scope', models.CharField(db_comment='비교 쌍 구성 범위 (동일 스타일/근접 이미지/연결 쌍 등)', max_length=40)),
                ('comparison_axis', models.CharField(db_comment='쌍대 비교 판단 축', default='Q_OVERALL_STYLE_EXECUTION', max_length=60)),
                ('context', models.JSONField(blank=True, db_comment='비교 가능한 스타일·계절·TPO 및 제시 순서 컨텍스트 JSON', default=dict)),
                ('outcome', models.CharField(choices=[('left', '왼쪽 우세'), ('right', '오른쪽 우세'), ('tie', '동등'), ('context_dependent', '상황 의존'), ('unassessable', '판단 불가')], db_comment='비교 결과 (left/right/tie/context_dependent/unassessable)', max_length=24)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, db_comment='사람 판단 확신도 (1~3, 미입력은 null)', null=True)),
                ('reason_axis', models.CharField(blank=True, db_comment='승패 판단에 가장 크게 기여한 패션 축', default='', max_length=60)),
                ('rationale', models.TextField(blank=True, db_comment='쌍대 비교 사유 또는 판단 불가 사유', default='')),
                ('rubric_version', models.CharField(db_comment='검수 질문·선택지 계약 버전', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='쌍대 비교 검수 시각')),
                ('dataset', models.ForeignKey(db_comment='소속 골든셋 버전 FK (golden_dataset.id)', on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_reviews', to='goldenset.goldendataset')),
                ('left_image', models.ForeignKey(db_comment='검수 화면 왼쪽 골든 이미지 FK (golden_image.id)', on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_reviews_as_left', to='goldenset.goldenimage')),
                ('right_image', models.ForeignKey(db_comment='검수 화면 오른쪽 골든 이미지 FK (golden_image.id)', on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_reviews_as_right', to='goldenset.goldenimage')),
            ],
            options={
                'db_table': 'goldenset"."golden_pairwise_review',
                'db_table_comment': '골든 이미지 두 장의 사람 상대 비교와 판단 근거',
                'indexes': [models.Index(fields=['dataset', 'comparison_axis'], name='golden_pair_dataset_5cb2c3_idx'), models.Index(fields=['dataset', 'reviewer_label'], name='golden_pair_dataset_94e0f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'pair_key', 'reviewer_label'), name='uq_golden_pairwise_reviewer'), models.CheckConstraint(condition=models.Q(('left_image', models.F('right_image')), _negated=True), name='ck_golden_pairwise_distinct_images'), models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 1), ('confidence__lte', 3)), _connector='OR'), name='ck_golden_pairwise_confidence_1_3')],
            },
        ),
    ]
