# Generated by Django 5.2.16 on 2026-08-11 00:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommend", "0005_dailylook"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="추천 결과 UUID (외부 노출 식별자)",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identity_id",
                    models.UUIDField(
                        db_comment="추천 결과를 소유한 회원 또는 게스트 채팅 identity UUID"
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(db_comment="추천이 생성된 채팅 세션 UUID"),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        db_comment="추천을 생성한 채팅 실행 UUID (실행당 결과 최대 1개)",
                        unique=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("WARDROBE_BASED", "옷장 기반 추천"),
                            ("NEW_ITEM", "신규 상품 포함 추천"),
                        ],
                        db_comment="추천 모드 (WARDROBE_BASED/NEW_ITEM)",
                        max_length=24,
                    ),
                ),
                (
                    "dataset_version",
                    models.CharField(
                        db_comment="추천에 사용한 골든셋 데이터 버전", max_length=128
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="추천 결과 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="추천 결과 마지막 수정 시각"
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_result",
                "db_table_comment": "채팅과 독립적으로 조회하는 추천 결과 묶음 (소유 identity·세션·실행·모드·골든셋 버전 보관)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identity_id", "-created_at"],
                        name="ix_reco_result_identity",
                    ),
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="ix_reco_result_session",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutfitComposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="코디 조합 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        db_comment="추천 결과 안의 코디 노출 순위 (1~3)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "검증 전 후보"),
                            ("VALIDATED", "검증 통과"),
                            ("REJECTED", "검증 실패"),
                        ],
                        db_comment="코디 검증 상태 (CANDIDATE/VALIDATED/REJECTED)",
                        default="CANDIDATE",
                        max_length=16,
                    ),
                ),
                (
                    "composition_fingerprint",
                    models.CharField(
                        blank=True,
                        db_comment="최종 아이템·순서·이미지 버전 기반 SHA-256 지문 (검증 전이면 빈 문자열)",
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "total_product_price",
                    models.PositiveBigIntegerField(
                        db_comment="코디에 포함된 신규 상품 가격 합계 (원)", default=0
                    ),
                ),
                (
                    "validation_reasons",
                    models.JSONField(
                        db_comment="Validator의 통과·실패 근거 JSON 배열", default=list
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        db_comment="추천은 가능하지만 사용자에게 안내할 검증 경고 JSON 배열",
                        default=list,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="코디 조합 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="코디 조합 마지막 수정 시각"
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        db_comment="추천 결과 FK (recommendation_result.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="recommend.recommendationresult",
                    ),
                ),
            ],
            options={
                "db_table": "outfit_composition",
                "db_table_comment": "추천 결과별 최종 코디 조합 (순위·검증 상태·가격·이미지 캐시 지문 보관)",
                "ordering": ["rank", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldenTemplateSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="골든 템플릿 스냅샷 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "golden_id",
                    models.CharField(
                        db_comment="골든셋 원본 코디 식별자", max_length=128
                    ),
                ),
                (
                    "point_id",
                    models.CharField(
                        db_comment="outfit_goldenset Qdrant point 식별자",
                        max_length=128,
                    ),
                ),
                (
                    "retrieval_score",
                    models.FloatField(
                        db_comment="최종 선택 시 골든 코디 검색·재정렬 점수"
                    ),
                ),
                (
                    "payload_snapshot",
                    models.JSONField(
                        db_comment="추천 당시 골든 코디 Qdrant payload JSON 스냅샷",
                        default=dict,
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        db_comment="골든 코디 선택 점수와 근거 JSON 배열", default=list
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="골든 템플릿 스냅샷 생성 시각"
                    ),
                ),
                (
                    "result",
                    models.OneToOneField(
                        db_comment="추천 결과 FK (recommendation_result.id, 결과당 선택 템플릿 1개)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="golden_template",
                        to="recommend.recommendationresult",
                    ),
                ),
            ],
            options={
                "db_table": "golden_template_snapshot",
                "db_table_comment": "추천 결과가 선택한 골든 코디 템플릿과 검색 점수·근거·payload 스냅샷",
            },
        ),
        migrations.CreateModel(
            name="OutfitCompositionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="코디 구성 아이템 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_comment="코디 내부 아이템 순서 (1부터 시작, 이미지 지문 계산에 사용)"
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        db_comment="골든 템플릿에서 정한 코디 슬롯 식별자",
                        max_length=64,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("WARDROBE", "옷장 아이템"), ("PRODUCT", "판매 상품")],
                        db_comment="최종 아이템 출처 (WARDROBE/PRODUCT)",
                        max_length=16,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_comment="옷장 또는 상품 원본 레코드 식별자", max_length=128
                    ),
                ),
                (
                    "source_collection",
                    models.CharField(
                        db_comment="후보를 조회한 Qdrant 컬렉션명", max_length=128
                    ),
                ),
                (
                    "source_point_id",
                    models.CharField(
                        db_comment="후보 아이템의 Qdrant point 식별자", max_length=128
                    ),
                ),
                (
                    "template_item_point_id",
                    models.CharField(
                        db_comment="이 슬롯의 교체 기준이 된 goldenset_items Qdrant point 식별자",
                        max_length=128,
                    ),
                ),
                (
                    "replacement_score",
                    models.FloatField(
                        blank=True,
                        db_comment="골든 기준 아이템과 최종 아이템의 교체 적합 점수 (미산정 시 NULL)",
                        null=True,
                    ),
                ),
                (
                    "image_ref",
                    models.CharField(
                        db_comment="추천·렌더에 사용한 아이템 이미지 S3 키 또는 검증된 URL",
                        max_length=1024,
                    ),
                ),
                (
                    "price_snapshot",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="추천 당시 상품 가격 (원, 옷장 아이템이면 NULL)",
                        null=True,
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        db_comment="아이템 선택·교체 근거 JSON 배열", default=list
                    ),
                ),
                (
                    "item_snapshot",
                    models.JSONField(
                        db_comment="추천 당시 아이템 표시 정보·태그·구매 링크 JSON 스냅샷",
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="코디 구성 아이템 생성 시각"
                    ),
                ),
                (
                    "composition",
                    models.ForeignKey(
                        db_comment="코디 조합 FK (outfit_composition.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recommend.outfitcomposition",
                    ),
                ),
            ],
            options={
                "db_table": "outfit_composition_item",
                "db_table_comment": "최종 코디의 슬롯별 옷장·상품 아이템과 교체 근거·표시 정보 스냅샷",
                "ordering": ["position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("composition", "slot"), name="uq_outfit_comp_item_slot"
                    ),
                    models.UniqueConstraint(
                        fields=("composition", "position"),
                        name="uq_outfit_comp_item_pos",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "composition",
                            "source_type",
                            "source_collection",
                            "source_id",
                        ),
                        name="uq_outfit_comp_item_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="ck_outfit_comp_item_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_type__in", ["WARDROBE", "PRODUCT"])
                        ),
                        name="ck_outfit_comp_item_source",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="outfitcomposition",
            index=models.Index(
                fields=["composition_fingerprint"], name="ix_outfit_comp_fingerprint"
            ),
        ),
        migrations.AddConstraint(
            model_name="outfitcomposition",
            constraint=models.UniqueConstraint(
                fields=("result", "rank"), name="uq_outfit_comp_result_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="outfitcomposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank__gte", 1), ("rank__lte", 3)),
                name="ck_outfit_comp_rank",
            ),
        ),
    ]
