# Generated by Django 5.2.16 on 2026-08-11 03:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_link_chat_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(db_comment='추천 피드백 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('LIKE', '좋아요'), ('DISLIKE', '싫어요')], db_comment='추천 카드 반응 (LIKE/DISLIKE)', max_length=8)),
                ('reason_codes', models.JSONField(blank=True, db_comment='피드백 사유 코드 문자열 배열 (최대 5개)', default=list)),
                ('comment', models.CharField(blank=True, db_comment='사용자 자유 의견 (최대 500자, 미입력 시 빈 문자열)', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='피드백 최초 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='피드백 마지막 수정 시각')),
                ('composition', models.OneToOneField(db_comment='평가 대상 코디 조합 FK (outfit_composition.id, 조합당 피드백 최대 1개)', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommend.outfitcomposition')),
            ],
            options={
                'db_table': 'recommendation_feedback',
                'db_table_comment': '추천 카드별 사용자 최신 반응과 선택 사유',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reaction__in', ['LIKE', 'DISLIKE'])), name='ck_reco_feedback_reaction')],
            },
        ),
    ]
