# Generated by Django 5.2.16 on 2026-08-11 05:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRenderJob',
            fields=[
                ('id', models.UUIDField(db_comment='코디 이미지 생성 작업 UUID (큐·SSE 공통 추적 ID)', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', '생성 대기'), ('PROCESSING', '생성 중'), ('SUCCEEDED', '생성 완료'), ('FAILED', '생성 실패')], db_comment='이미지 생성 상태 (QUEUED/PROCESSING/SUCCEEDED/FAILED)', default='QUEUED', max_length=16)),
                ('composition_fingerprint', models.CharField(db_comment='작업 접수 당시 코디 조합 SHA-256 지문', max_length=64)),
                ('render_fingerprint', models.CharField(db_comment='코디 지문·모델·프롬프트·출력 설정을 합친 렌더 캐시 SHA-256 지문', max_length=64)),
                ('output_s3_bucket', models.CharField(blank=True, db_comment='생성 결과를 보관한 비공개 S3 버킷 (미완료이면 빈 문자열)', default='', max_length=255)),
                ('output_s3_key', models.CharField(blank=True, db_comment='생성 결과 S3 객체 키 (외부 API에는 직접 노출하지 않음)', default='', max_length=512)),
                ('output_media_type', models.CharField(blank=True, db_comment='생성 결과 MIME 타입 (image/jpeg/image/png/image/webp, 미완료이면 빈 문자열)', default='', max_length=50)),
                ('output_bytes', models.PositiveIntegerField(blank=True, db_comment='생성 결과 이미지 크기 (bytes, 미완료이면 NULL)', null=True)),
                ('provider', models.CharField(blank=True, db_comment='이미지 생성 제공자 (예: openrouter, 캐시 결과도 원 생성 제공자 기록)', default='', max_length=32)),
                ('model', models.CharField(blank=True, db_comment='이미지 생성 모델명 (예: qwen/qwen-image-3-pro)', default='', max_length=128)),
                ('prompt_version', models.CharField(blank=True, db_comment='이미지 생성 프롬프트 버전', default='', max_length=64)),
                ('reference_count', models.PositiveSmallIntegerField(db_comment='최종 이미지 생성에 사용한 참조 아이템 이미지 수', default=0)),
                ('usage', models.JSONField(blank=True, db_comment='이미지 제공자가 반환한 사용량·비용 JSON', default=dict)),
                ('cache_hit', models.BooleanField(db_comment='동일 렌더 지문의 기존 생성 결과를 재사용했는지 여부', default=False)),
                ('attempts', models.PositiveSmallIntegerField(db_comment='이미지 워커 처리 시도 횟수 (재시도 포함)', default=0)),
                ('error_code', models.CharField(blank=True, db_comment='실패 오류 코드 (성공 또는 대기 상태이면 빈 문자열)', default='', max_length=64)),
                ('error_message', models.CharField(blank=True, db_comment='사용자에게 노출 가능한 실패 메시지 (성공 또는 대기 상태이면 빈 문자열)', default='', max_length=500)),
                ('enqueued_at', models.DateTimeField(blank=True, db_comment='Redis pending 큐 적재 확인 시각 (적재 확인 전이면 NULL)', null=True)),
                ('started_at', models.DateTimeField(blank=True, db_comment='이미지 워커가 마지막 처리를 시작한 시각', null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_comment='이미지 생성 성공 또는 최종 실패 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='이미지 생성 작업 최초 접수 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='이미지 생성 작업 마지막 수정 시각')),
                ('composition', models.OneToOneField(db_comment='이미지를 생성할 검증 완료 코디 조합 FK (outfit_composition.id)', on_delete=django.db.models.deletion.CASCADE, related_name='render_job', to='recommend.outfitcomposition')),
            ],
            options={
                'db_table': 'outfit_render_job',
                'db_table_comment': '추천 카드별 비동기 착용 이미지 생성 상태·비공개 S3 결과·캐시 근거',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ix_outfit_render_status'), models.Index(fields=['render_fingerprint'], name='ix_outfit_render_fprint')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'PROCESSING', 'SUCCEEDED', 'FAILED'])), name='ck_outfit_render_status')],
            },
        ),
    ]
