# Generated by Django 5.2.16 on 2026-08-16 08:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_recommendation_result_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.UUIDField(db_comment='저장 코디 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='코디를 최초 저장한 시각')),
                ('composition', models.ForeignKey(db_comment='저장 대상 검증 완료 추천 코디 FK (outfit_composition.id)', on_delete=django.db.models.deletion.CASCADE, related_name='saved_records', to='recommend.outfitcomposition')),
                ('user', models.ForeignKey(db_comment='코디를 저장한 회원 FK (게스트 저장 불가)', on_delete=django.db.models.deletion.CASCADE, related_name='saved_outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_outfit',
                'db_table_comment': '회원이 저장한 추천 코디와 최초 저장 시각',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'composition'), name='uq_saved_outfit_user_comp')],
            },
        ),
    ]
