# Generated by Django 5.2.16 on 2026-08-16 08:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_savedoutfit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClickEvent',
            fields=[
                ('id', models.UUIDField(db_comment='상품 클릭 이벤트 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id_snapshot', models.UUIDField(db_comment='클릭 당시 추천 결과 UUID 스냅샷')),
                ('composition_id_snapshot', models.UUIDField(db_comment='클릭 당시 추천 카드 UUID 스냅샷')),
                ('persona_id', models.CharField(blank=True, db_comment='클릭 당시 스타일리스트 ID (기본 추천이면 빈 문자열)', default='', max_length=32)),
                ('source_collection', models.CharField(db_comment='클릭 당시 상품 원본 컬렉션 스냅샷', max_length=128)),
                ('source_id', models.CharField(db_comment='클릭 당시 상품 원본 레코드 식별자 스냅샷', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='상품 클릭 이벤트 수집 시각')),
                ('item', models.ForeignKey(db_comment='클릭한 추천 카드의 판매 상품 아이템 FK', on_delete=django.db.models.deletion.CASCADE, related_name='product_click_events', to='recommend.outfitcompositionitem')),
                ('user', models.ForeignKey(db_comment='상품을 클릭한 회원 FK (게스트 수집 불가)', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_product_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_click_event',
                'db_table_comment': '추천 카드 판매 상품 클릭 참고 행동 이벤트',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'item', '-created_at'], name='ix_prod_click_user_item')],
            },
        ),
    ]
