# Generated by Django 5.2.16 on 2026-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0015_productclickevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="productclickevent",
            name="engagement_duration_ms",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_comment=(
                    "외부 판매처 이동 후 앱 복귀까지의 근사 체류 시간"
                    "(ms, 미수집 시 NULL)"
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productclickevent",
            name="engagement_recorded_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="상품 클릭 근사 체류 시간을 마지막으로 수집한 시각",
                null=True,
            ),
        ),
    ]
