# Generated by Django 5.2.17 on 2026-08-18 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0016_productclickevent_engagement_duration_ms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(db_comment='찜 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id_snapshot', models.UUIDField(blank=True, db_comment='담은 추천 결과 UUID 스냅샷', null=True)),
                ('composition_id_snapshot', models.UUIDField(blank=True, db_comment='담은 추천 카드 UUID 스냅샷', null=True)),
                ('source_collection', models.CharField(blank=True, db_comment='상품 후보를 조회한 Qdrant 컬렉션명', default='', max_length=128)),
                ('source_id', models.CharField(blank=True, db_comment='상품 카탈로그 원본 식별자 (naver_product_id / eleven_product_id)', default='', max_length=128)),
                ('display_name', models.CharField(db_comment='목록에 보여줄 상품명 (담은 시점 스냅샷)', max_length=500)),
                ('brand', models.CharField(blank=True, db_comment='브랜드명 (카탈로그에 있으면 채우고, 없으면 빈 문자열)', default='', max_length=200)),
                ('price_snapshot', models.PositiveBigIntegerField(blank=True, db_comment='담은 시점 가격 (원, 미상이면 NULL)', null=True)),
                ('image_ref', models.CharField(blank=True, db_comment='상품 이미지 S3 키 또는 검증된 URL', default='', max_length=1024)),
                ('purchase_url', models.TextField(blank=True, db_comment='판매처 상품 주소 (없으면 앱이 검색 주소를 만든다)', default='')),
                ('slot', models.CharField(blank=True, db_comment='담을 때의 코디 슬롯 (상의/하의 등, 예산 비교에 쓴다)', default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='찜한 시각')),
                ('item', models.ForeignKey(blank=True, db_comment='담은 시점의 코디 구성 아이템 FK (추천 삭제 시 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_entries', to='recommend.outfitcompositionitem')),
                ('user', models.ForeignKey(db_comment='찜한 회원 FK (users.id)', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_item',
                'db_table_comment': '회원이 담아 둔 추천 판매 상품과 담은 시점 스냅샷',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ix_wishlist_user_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('user', 'source_collection', 'source_id'), name='uq_wishlist_user_source')],
            },
        ),
    ]
