# Generated by Django 5.2.16 on 2026-08-04 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0003_table_column_comments'),
        ('users', '0010_system_table_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.UUIDField(db_comment='캘린더 UUID (이미지 작업과 callback 멱등성 식별자)', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_comment='착장 날짜 (사용자별 하루 한 건)')),
                ('source_type', models.CharField(choices=[('PHOTO_UPLOAD', '사진 업로드'), ('WARDROBE_SELECTED', '옷장 직접 선택')], db_comment='캘린더 등록 경로 (PHOTO_UPLOAD/WARDROBE_SELECTED)', max_length=24)),
                ('image_s3_key', models.CharField(db_comment='캘린더 대표 이미지 S3 키 (캘린더 소유 경로)', max_length=512)),
                ('schedule', models.TextField(blank=True, db_comment='사용자가 입력한 일정 설명', default='')),
                ('tpo', models.JSONField(blank=True, db_comment='착장 상황(TPO) 코드 또는 문자열 목록 JSON', default=list)),
                ('weather_snapshot', models.JSONField(blank=True, db_comment='등록 당시 날씨 스냅샷 JSON (위치 정보 없으면 NULL)', null=True)),
                ('hashtags', models.JSONField(blank=True, db_comment='캘린더 해시태그 문자열 목록 JSON', default=list)),
                ('status', models.CharField(choices=[('REGISTERED', '등록'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패')], db_comment='이미지 처리 상태 (REGISTERED/PROCESSING/COMPLETED/FAILED)', default='REGISTERED', max_length=16)),
                ('manifest_s3_key', models.CharField(blank=True, db_comment='이미지 처리 결과 manifest S3 키', default='', max_length=512)),
                ('processing_error_code', models.CharField(blank=True, db_comment='전체 이미지 처리 실패 오류 코드', default='', max_length=64)),
                ('processing_error_message', models.TextField(blank=True, db_comment='전체 이미지 처리 실패 오류 메시지', default='')),
                ('processing_started_at', models.DateTimeField(blank=True, db_comment='이미지 프로세서 작업 시작 시각', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, db_comment='이미지 프로세서 작업 종료 시각', null=True)),
                ('callback_applied_at', models.DateTimeField(blank=True, db_comment='최종 callback을 DB에 최초 반영한 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='캘린더 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='캘린더 수정 시각')),
                ('user', models.ForeignKey(db_comment='캘린더 소유 사용자 FK (users.id)', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_entry',
                'db_table_comment': '사용자별 하루 착장 캘린더 (대표 사진 한 장과 이미지 처리 상태)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarWardrobeItem',
            fields=[
                ('id', models.UUIDField(db_comment='캘린더-옷장 아이템 연결 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(db_comment='캘린더 안의 옷장 아이템 표시 순서 (0부터 시작)', default=0)),
                ('snapshot', models.JSONField(blank=True, db_comment='연결 당시 옷장 아이템의 이미지·이름·카테고리·태그 스냅샷 JSON', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='캘린더-옷장 아이템 연결 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='캘린더-옷장 아이템 연결 수정 시각')),
                ('calendar', models.ForeignKey(db_comment='연결 대상 캘린더 FK (calendar_entry.id)', on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_links', to='style_calendar.calendarentry')),
                ('wardrobe_item', models.ForeignKey(db_comment='연결 대상 옷장 아이템 FK (wardrobe_item.id)', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'calendar_wardrobe_item',
                'db_table_comment': '캘린더와 옷장 아이템의 N:N 연결 정보',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='wardrobe_items',
            field=models.ManyToManyField(blank=True, related_name='calendar_entries', through='style_calendar.CalendarWardrobeItem', through_fields=('calendar', 'wardrobe_item'), to='wardrobe.wardrobeitem'),
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.UUIDField(db_comment='캘린더 아이템 UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_status', models.CharField(choices=[('EXTRACTED', '추출 완료'), ('FAILED', '추출 실패')], db_comment='백엔드 내부 처리 상태 (EXTRACTED/FAILED, 사용자 작업 상태 아님)', max_length=16)),
                ('processor_item_id', models.CharField(db_comment='이미지 프로세서 결과 아이템 식별자 (callback 중복 방지)', max_length=128)),
                ('image_s3_key', models.CharField(blank=True, db_comment='캘린더 소유 아이템 이미지 S3 키 (처리 실패 시 빈 문자열)', default='', max_length=512)),
                ('category', models.CharField(blank=True, db_comment='이미지 프로세서가 추출한 의류 카테고리', default='', max_length=100)),
                ('tags', models.JSONField(blank=True, db_comment='아이템 태그 문자열 목록 또는 구조화 JSON', default=list)),
                ('bbox', models.JSONField(blank=True, db_comment='원본 사진 내 감지 영역 JSON (x/y/width/height)', null=True)),
                ('sort_order', models.PositiveIntegerField(db_comment='캘린더 안의 아이템 표시 순서 (0부터 시작)', default=0)),
                ('processing_error', models.TextField(blank=True, db_comment='아이템 단위 이미지 처리 오류 메시지', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='캘린더 아이템 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='캘린더 아이템 수정 시각')),
                ('calendar', models.ForeignKey(db_comment='소속 캘린더 FK (calendar_entry.id)', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='style_calendar.calendarentry')),
            ],
            options={
                'db_table': 'calendar_item',
                'db_table_comment': '캘린더 사진에서 이미지 프로세서가 추출한 착장 아이템 결과',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['calendar', 'sort_order'], name='cal_item_calendar_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'processor_item_id'), name='uq_cal_item_processor')],
            },
        ),
        migrations.AddIndex(
            model_name='calendarwardrobeitem',
            index=models.Index(fields=['calendar', 'sort_order'], name='cal_wardrobe_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarwardrobeitem',
            constraint=models.UniqueConstraint(fields=('calendar', 'wardrobe_item'), name='uq_cal_wardrobe_link'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['status', 'created_at'], name='cal_entry_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uq_calendar_user_date'),
        ),
    ]
