# Generated by Django 5.2.16 on 2026-08-05 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_calendar', '0001_initial'),
        ('wardrobe', '0003_table_column_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarentry',
            name='manifest_s3_key',
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='wardrobe_upload_job',
            field=models.OneToOneField(blank=True, db_comment='사진 업로드 처리에 재사용한 옷장 job FK (wardrobe_upload_job.id, 직접 선택 등록은 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entry', to='wardrobe.wardrobeuploadjob'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='id',
            field=models.UUIDField(db_comment='캘린더 UUID (외부 노출 식별자)', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CalendarItem',
        ),
    ]
