# Generated by Django 5.2.16 on 2026-08-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_calendar', '0002_remove_calendarentry_manifest_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='skipped_categories',
            field=models.JSONField(blank=True, db_comment='입은 옷 지정과 겹쳐 사진 등록에서 제외한 옷장 대분류 목록 JSON (예: 상의/하의)', default=list),
        ),
    ]
