# Generated by Django 5.2.17 on 2026-08-07 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("style_calendar", "0002_remove_calendarentry_manifest_s3_key_and_more"),
        ("wardrobe", "0003_table_column_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LookbookPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="룩북 UUID (외부 노출 식별자)",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("PHOTO_UPLOAD", "룩 사진 업로드"),
                            ("WARDROBE_SELECTED", "옷장 직접 선택"),
                        ],
                        db_comment="룩북 등록 경로 (PHOTO_UPLOAD/WARDROBE_SELECTED)",
                        max_length=24,
                    ),
                ),
                (
                    "image_s3_key",
                    models.CharField(
                        db_comment="룩북 대표 이미지 S3 키 (룩북 소유 경로)",
                        max_length=512,
                    ),
                ),
                (
                    "schedule",
                    models.TextField(
                        blank=True, db_comment="사용자가 입력한 일정 설명", default=""
                    ),
                ),
                (
                    "tpo",
                    models.JSONField(
                        blank=True,
                        db_comment="착장 상황(TPO) 코드 또는 문자열 목록 JSON",
                        default=list,
                    ),
                ),
                (
                    "hashtags",
                    models.JSONField(
                        blank=True,
                        db_comment="룩북 해시태그 문자열 목록 JSON",
                        default=list,
                    ),
                ),
                (
                    "skipped_categories",
                    models.JSONField(
                        blank=True,
                        db_comment="입은 옷 지정과 겹쳐 사진 등록에서 제외한 옷장 대분류 목록 JSON (예: 상의/하의)",
                        default=list,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "등록"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        db_comment="이미지 처리 상태 (REGISTERED/PROCESSING/COMPLETED/FAILED)",
                        default="REGISTERED",
                        max_length=16,
                    ),
                ),
                (
                    "processing_error_code",
                    models.CharField(
                        blank=True,
                        db_comment="전체 이미지 처리 실패 오류 코드",
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "processing_error_message",
                    models.TextField(
                        blank=True,
                        db_comment="전체 이미지 처리 실패 오류 메시지",
                        default="",
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="이미지 프로세서 작업 시작 시각",
                        null=True,
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="이미지 프로세서 작업 종료 시각",
                        null=True,
                    ),
                ),
                (
                    "callback_applied_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="최종 callback을 DB에 최초 반영한 시각",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="룩북 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="룩북 수정 시각"),
                ),
                (
                    "calendar_entry",
                    models.OneToOneField(
                        blank=True,
                        db_comment="'캘린더에도 기록'으로 함께 만든 캘린더 FK (calendar_entry.id, 캘린더를 남기지 않으면 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookbook_post",
                        to="style_calendar.calendarentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="룩북 소유 사용자 FK (users.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookbook_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wardrobe_upload_job",
                    models.OneToOneField(
                        blank=True,
                        db_comment="룩 사진 처리에 재사용한 옷장 job FK (wardrobe_upload_job.id, 옷장 직접 선택 등록은 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookbook_post",
                        to="wardrobe.wardrobeuploadjob",
                    ),
                ),
            ],
            options={
                "db_table": "lookbook_post",
                "db_table_comment": "사용자가 올린 룩 한 벌 (대표 사진·입은 옷·일정·해시태그와 이미지 처리 상태)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LookbookWardrobeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="룩북-옷장 아이템 연결 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("SELECTED", "사용자 직접 선택"),
                            ("EXTRACTED", "룩 사진에서 추출"),
                        ],
                        db_comment="아이템이 붙은 경로 (SELECTED: 직접 선택 / EXTRACTED: 사진 추출)",
                        default="SELECTED",
                        max_length=16,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_comment="룩북 안의 옷장 아이템 표시 순서 (0부터 시작)",
                        default=0,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="연결 당시 옷장 아이템의 이미지·이름·카테고리·태그 스냅샷 JSON",
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="룩북-옷장 아이템 연결 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="룩북-옷장 아이템 연결 수정 시각"
                    ),
                ),
                (
                    "lookbook",
                    models.ForeignKey(
                        db_comment="연결 대상 룩북 FK (lookbook_post.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_links",
                        to="lookbook.lookbookpost",
                    ),
                ),
                (
                    "wardrobe_item",
                    models.ForeignKey(
                        db_comment="연결 대상 옷장 아이템 FK (wardrobe_item.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookbook_links",
                        to="wardrobe.wardrobeitem",
                    ),
                ),
            ],
            options={
                "db_table": "lookbook_wardrobe_item",
                "db_table_comment": "룩북과 옷장 아이템의 N:N 연결 정보",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="lookbookpost",
            name="wardrobe_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="lookbook_posts",
                through="lookbook.LookbookWardrobeItem",
                through_fields=("lookbook", "wardrobe_item"),
                to="wardrobe.wardrobeitem",
            ),
        ),
        migrations.AddIndex(
            model_name="lookbookwardrobeitem",
            index=models.Index(
                fields=["lookbook", "sort_order"], name="lookbook_wardrobe_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lookbookwardrobeitem",
            constraint=models.UniqueConstraint(
                fields=("lookbook", "wardrobe_item"), name="uq_lookbook_wardrobe_link"
            ),
        ),
        migrations.AddIndex(
            model_name="lookbookpost",
            index=models.Index(
                fields=["user", "-created_at"], name="lookbook_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lookbookpost",
            index=models.Index(
                fields=["status", "created_at"], name="lookbook_status_created_idx"
            ),
        ),
    ]
