# Generated by Django 5.2.17 on 2026-08-13 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookbook', '0001_initial'),
        ('style_calendar', '0002_remove_calendarentry_manifest_s3_key_and_more'),
        ('wardrobe', '0006_wardrobeitem_added_to_closet_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbookpost',
            name='is_public',
            field=models.BooleanField(db_comment='전체 공개 여부 (true: 앱 사용자 전체가 둘러보기에서 볼 수 있음). 룩북은 친구 단위 공유를 두지 않는다 — 내 것이거나 전체 공개거나 둘 중 하나다.', default=False, verbose_name='전체 공개 여부'),
        ),
        migrations.AddIndex(
            model_name='lookbookpost',
            index=models.Index(fields=['is_public', '-created_at'], name='lookbook_public_created_idx'),
        ),
    ]
