# Generated by Django 5.2.16 on 2026-07-29 01:01

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="weatherarea",
            table_comment="기상청 수집 대상 구역 마스터 (단기 격자 + 중기 예보구역)",
        ),
        migrations.AlterModelTableComment(
            name="weathermidlandraw",
            table_comment="기상청 중기 육상예보 원본 (구역×발표시각×예보일×오전/오후당 1행)",
        ),
        migrations.AlterModelTableComment(
            name="weathermidtempraw",
            table_comment="기상청 중기 기온예보 원본 (구역×발표시각×예보일당 1행)",
        ),
        migrations.AlterModelTableComment(
            name="weathernowcastraw",
            table_comment="기상청 초단기실황 원본 (구역×발표시각당 1행)",
        ),
        migrations.AlterModelTableComment(
            name="weathershortraw",
            table_comment="기상청 단기예보 원본 (구역×발표시각×예보시각당 1행)",
        ),
        migrations.AlterModelTableComment(
            name="weatherveryshortraw",
            table_comment="기상청 초단기예보 원본 (구역×발표시각×예보시각당 1행)",
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="address_label",
            field=models.CharField(
                blank=True,
                db_comment="표시용 전체 주소 라벨",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="area_type",
            field=models.CharField(
                db_comment="구역 유형 (GRID: 단기 격자 / MID_LAND: 중기 육상 / MID_TEMP: 중기 기온)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="eupmyeondong",
            field=models.CharField(
                blank=True, db_comment="읍/면/동", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="is_active",
            field=models.BooleanField(
                db_comment="수집 대상 여부 (false면 수집 제외)",
                db_default=True,
                default=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                db_comment="위도",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                db_comment="경도",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="name",
            field=models.CharField(
                db_comment="구역 이름 (행정동/예보구역명)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="nx",
            field=models.SmallIntegerField(
                blank=True, db_comment="기상청 격자 X 좌표 (GRID 전용)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="ny",
            field=models.SmallIntegerField(
                blank=True, db_comment="기상청 격자 Y 좌표 (GRID 전용)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="reg_id",
            field=models.CharField(
                blank=True,
                db_comment="기상청 중기예보 구역 코드 (MID_* 전용)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="sido",
            field=models.CharField(
                blank=True, db_comment="시/도", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="sigungu",
            field=models.CharField(
                blank=True, db_comment="시/군/구", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherarea",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="area",
            field=models.ForeignKey(
                db_comment="예보 구역 FK (weather_area.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mid_lands",
                to="weather.weatherarea",
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="base_datetime",
            field=models.DateTimeField(db_comment="발표 기준 시각 (tmFc)"),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집 시각"),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="forecast_date",
            field=models.DateField(db_comment="예보 대상 날짜 (발표일 +4~+10일)"),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="forecast_period",
            field=models.CharField(
                choices=[("AM", "Am"), ("PM", "Pm")],
                db_comment="예보 구간 (AM: 오전 / PM: 오후)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="precipitation_probability",
            field=models.DecimalField(
                blank=True,
                db_comment="강수 확률 (백분율)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="raw_data",
            field=models.JSONField(
                blank=True, db_comment="기상청 API 원본 응답 JSON", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="sky_label",
            field=models.CharField(
                blank=True,
                db_comment="날씨 예보 문구 (맑음/구름많고 비 등)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathermidlandraw",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="area",
            field=models.ForeignKey(
                db_comment="예보 구역 FK (weather_area.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mid_temps",
                to="weather.weatherarea",
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="base_datetime",
            field=models.DateTimeField(db_comment="발표 기준 시각 (tmFc)"),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집 시각"),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="forecast_date",
            field=models.DateField(db_comment="예보 대상 날짜 (발표일 +4~+10일)"),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="max_temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="일 최고기온 (℃)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="min_temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="일 최저기온 (℃)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="raw_data",
            field=models.JSONField(
                blank=True, db_comment="기상청 API 원본 응답 JSON", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="weathermidtempraw",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="area",
            field=models.ForeignKey(
                db_comment="예보 구역 FK (weather_area.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nowcasts",
                to="weather.weatherarea",
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="base_datetime",
            field=models.DateTimeField(
                db_comment="발표 기준 시각 (base_date+base_time)"
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집 시각"),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="humidity",
            field=models.DecimalField(
                blank=True,
                db_comment="습도 (REH, 백분율)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="precipitation_amount",
            field=models.CharField(
                blank=True,
                db_comment="1시간 강수량 (RN1, 범주 문자열)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="precipitation_type_code",
            field=models.CharField(
                blank=True, db_comment="강수 형태 코드 (PTY)", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="precipitation_type_label",
            field=models.CharField(
                blank=True,
                db_comment="강수 형태 라벨 (없음/비/눈 등)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="raw_data",
            field=models.JSONField(
                blank=True, db_comment="기상청 API 원본 응답 JSON", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="기온 (℃, T1H)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="wind_direction_deg",
            field=models.DecimalField(
                blank=True,
                db_comment="풍향 (deg, VEC)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="wind_direction_label",
            field=models.CharField(
                blank=True, db_comment="풍향 라벨 (N/NE 등)", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathernowcastraw",
            name="wind_speed",
            field=models.DecimalField(
                blank=True,
                db_comment="풍속 (m/s, WSD)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="area",
            field=models.ForeignKey(
                db_comment="예보 구역 FK (weather_area.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shorts",
                to="weather.weatherarea",
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="base_datetime",
            field=models.DateTimeField(
                db_comment="발표 기준 시각 (base_date+base_time)"
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집 시각"),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="forecast_date",
            field=models.DateField(db_comment="예보 대상 날짜 (fcstDate)"),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="forecast_time",
            field=models.TimeField(db_comment="예보 대상 시각 (fcstTime)"),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="humidity",
            field=models.DecimalField(
                blank=True,
                db_comment="습도 (REH, 백분율)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="max_temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="일 최고기온 (℃, TMX)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="min_temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="일 최저기온 (℃, TMN)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="precipitation_amount",
            field=models.CharField(
                blank=True,
                db_comment="1시간 강수량 (PCP, 범주 문자열)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="precipitation_probability",
            field=models.DecimalField(
                blank=True,
                db_comment="강수 확률 (POP, 백분율)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="precipitation_type_code",
            field=models.CharField(
                blank=True, db_comment="강수 형태 코드 (PTY)", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="precipitation_type_label",
            field=models.CharField(
                blank=True, db_comment="강수 형태 라벨", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="raw_data",
            field=models.JSONField(
                blank=True, db_comment="기상청 API 원본 응답 JSON", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="sky_code",
            field=models.CharField(
                blank=True, db_comment="하늘 상태 코드 (SKY)", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="sky_label",
            field=models.CharField(
                blank=True,
                db_comment="하늘 상태 라벨 (맑음/구름많음/흐림)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="기온 (℃, TMP)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="wind_direction_deg",
            field=models.DecimalField(
                blank=True,
                db_comment="풍향 (deg, VEC)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="wind_direction_label",
            field=models.CharField(
                blank=True, db_comment="풍향 라벨", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weathershortraw",
            name="wind_speed",
            field=models.DecimalField(
                blank=True,
                db_comment="풍속 (m/s, WSD)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="area",
            field=models.ForeignKey(
                db_comment="예보 구역 FK (weather_area.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="very_shorts",
                to="weather.weatherarea",
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="base_datetime",
            field=models.DateTimeField(
                db_comment="발표 기준 시각 (base_date+base_time)"
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="collected_at",
            field=models.DateTimeField(db_comment="수집 시각"),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="created_at",
            field=models.DateTimeField(
                db_comment="행 생성 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="forecast_date",
            field=models.DateField(db_comment="예보 대상 날짜 (fcstDate)"),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="forecast_time",
            field=models.TimeField(db_comment="예보 대상 시각 (fcstTime)"),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="humidity",
            field=models.DecimalField(
                blank=True,
                db_comment="습도 (REH, 백분율)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="precipitation_amount",
            field=models.CharField(
                blank=True,
                db_comment="1시간 강수량 (RN1, 범주 문자열)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="precipitation_type_code",
            field=models.CharField(
                blank=True, db_comment="강수 형태 코드 (PTY)", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="precipitation_type_label",
            field=models.CharField(
                blank=True, db_comment="강수 형태 라벨", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="raw_data",
            field=models.JSONField(
                blank=True, db_comment="기상청 API 원본 응답 JSON", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="sky_code",
            field=models.CharField(
                blank=True, db_comment="하늘 상태 코드 (SKY)", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="sky_label",
            field=models.CharField(
                blank=True,
                db_comment="하늘 상태 라벨 (맑음/구름많음/흐림)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                db_comment="기온 (℃, T1H)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="행 수정 시각",
                db_default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="wind_direction_deg",
            field=models.DecimalField(
                blank=True,
                db_comment="풍향 (deg, VEC)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="wind_direction_label",
            field=models.CharField(
                blank=True, db_comment="풍향 라벨", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="weatherveryshortraw",
            name="wind_speed",
            field=models.DecimalField(
                blank=True,
                db_comment="풍속 (m/s, WSD)",
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        # 자동 생성 id PK는 모델 필드가 아니라 db_comment로 커버되지 않는다 → raw SQL
        migrations.RunSQL(
            sql=[
                "COMMENT ON COLUMN weather_area.id IS '예보 구역 PK (자동 증가)';",
                "COMMENT ON COLUMN weather_nowcast_raw.id IS '실황 Raw PK (자동 증가)';",
                "COMMENT ON COLUMN weather_very_short_raw.id IS '초단기예보 Raw PK (자동 증가)';",
                "COMMENT ON COLUMN weather_short_raw.id IS '단기예보 Raw PK (자동 증가)';",
                "COMMENT ON COLUMN weather_mid_land_raw.id IS '중기 육상예보 Raw PK (자동 증가)';",
                "COMMENT ON COLUMN weather_mid_temp_raw.id IS '중기 기온예보 Raw PK (자동 증가)';",
            ],
            reverse_sql=[
                "COMMENT ON COLUMN weather_area.id IS NULL;",
                "COMMENT ON COLUMN weather_nowcast_raw.id IS NULL;",
                "COMMENT ON COLUMN weather_very_short_raw.id IS NULL;",
                "COMMENT ON COLUMN weather_short_raw.id IS NULL;",
                "COMMENT ON COLUMN weather_mid_land_raw.id IS NULL;",
                "COMMENT ON COLUMN weather_mid_temp_raw.id IS NULL;",
            ],
        ),
    ]
