# Generated by Django 5.2.16 on 2026-08-11 01:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="채팅 메시지 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveBigIntegerField(
                        db_comment="세션 내부 메시지 순서 (1부터 시작)"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "사용자"),
                            ("ASSISTANT", "AI"),
                            ("SYSTEM", "시스템"),
                            ("TOOL", "도구"),
                        ],
                        db_comment="메시지 역할 (USER/ASSISTANT/SYSTEM/TOOL)",
                        max_length=12,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        db_comment="채팅 메시지 본문 (첨부파일 전용 메시지이면 빈 문자열 가능)",
                        default="",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "처리 대기"),
                            ("PROCESSING", "처리 중"),
                            ("COMPLETED", "처리 완료"),
                            ("FAILED", "처리 실패"),
                        ],
                        db_comment="메시지 처리 상태 (PENDING/PROCESSING/COMPLETED/FAILED)",
                        default="COMPLETED",
                        max_length=16,
                    ),
                ),
                (
                    "client_message_id",
                    models.CharField(
                        blank=True,
                        db_comment="클라이언트 재전송 중복 방지 ID (서버 메시지이면 NULL)",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="추천 결과·실행 ID·오류 등 메시지 부가정보 JSON",
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="채팅 메시지 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="채팅 메시지 마지막 수정 시각"
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "db_table_comment": "세션별 순서·역할·처리 상태·중복 방지 ID를 가진 채팅 메시지",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ChatIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="채팅 identity UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[("MEMBER", "회원"), ("GUEST", "게스트")],
                        db_comment="채팅 identity 유형 (MEMBER/GUEST)",
                        max_length=12,
                    ),
                ),
                (
                    "guest_token_hash",
                    models.CharField(
                        blank=True,
                        db_comment="게스트 원문 토큰의 SHA-256 HMAC 해시 (회원이면 NULL)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="게스트 identity 만료 시각 (회원이면 NULL, 마지막 활동부터 7일)",
                        null=True,
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        db_comment="채팅 identity의 마지막 활동 시각",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="게스트 대화가 회원에게 이전된 시각 (미이전이면 NULL)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="채팅 identity 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="채팅 identity 마지막 수정 시각"
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="게스트 대화를 이전받은 회원 채팅 identity FK (미이전이면 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_guest_identities",
                        to="chat.chatidentity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_comment="회원 사용자 FK (users.id, 게스트이면 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_identity",
                "db_table_comment": "회원과 게스트 채팅 소유권 및 게스트 토큰 만료·이전 기록",
            },
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="채팅 첨부파일 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(db_comment="비공개 S3 객체 키", max_length=512),
                ),
                (
                    "mime_type",
                    models.CharField(db_comment="첨부파일 MIME 타입", max_length=100),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(db_comment="첨부파일 크기 (bytes)"),
                ),
                (
                    "sha256",
                    models.CharField(
                        db_comment="첨부파일 내용 SHA-256 해시", max_length=64
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "분석 안 함"),
                            ("QUEUED", "분석 대기"),
                            ("PROCESSING", "분석 중"),
                            ("SUCCEEDED", "분석 완료"),
                            ("FAILED", "분석 실패"),
                        ],
                        db_comment="첨부 이미지 분석 상태 (NOT_REQUESTED/QUEUED/PROCESSING/SUCCEEDED/FAILED)",
                        default="NOT_REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="채팅 첨부파일 메타데이터 생성 시각",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_comment="첨부파일이 속한 채팅 메시지 FK (chat_message.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "chat_attachment",
                "db_table_comment": "채팅 메시지에 연결된 비공개 S3 첨부파일 메타데이터",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="채팅 세션 UUID (외부 노출 식별자)",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("WARDROBE_BASED", "옷장 기반 추천"),
                            ("NEW_ITEM", "신규 상품 포함 추천"),
                        ],
                        db_comment="세션 생성 후 변경할 수 없는 추천 모드 (WARDROBE_BASED/NEW_ITEM)",
                        max_length=24,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_comment="사용자 지정 또는 자동 생성 세션 제목",
                        default="",
                        max_length=120,
                    ),
                ),
                (
                    "persona_profile_id",
                    models.UUIDField(
                        blank=True,
                        db_comment="세션에 적용할 페르소나 프로필 UUID (미지정이면 활성 기본값)",
                        null=True,
                    ),
                ),
                (
                    "context_state",
                    models.JSONField(
                        blank=True,
                        db_comment="세션의 구조화 추천 조건과 컨텍스트 버전 JSON",
                        default=dict,
                    ),
                ),
                (
                    "conversation_summary",
                    models.TextField(
                        blank=True,
                        db_comment="오래된 메시지를 압축한 대화 요약",
                        default="",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="마지막 메시지 생성 시각 (메시지가 없으면 NULL)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="채팅 세션 생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="채팅 세션 마지막 수정 시각"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="사용자가 세션을 삭제한 시각 (소프트 삭제, 활성 세션이면 NULL)",
                        null=True,
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        db_comment="채팅 소유 identity FK (chat_identity.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="chat.chatidentity",
                    ),
                ),
                (
                    "parent_session",
                    models.ForeignKey(
                        blank=True,
                        db_comment="모드 변경 시 조건을 이어받은 원본 세션 FK (일반 세션이면 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_sessions",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_session",
                "db_table_comment": "추천 모드·조건·대화 요약을 보관하는 회원·게스트 채팅 세션",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                db_comment="채팅 세션 FK (chat_session.id)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
            ),
        ),
        migrations.AddIndex(
            model_name="chatidentity",
            index=models.Index(
                fields=["identity_type", "expires_at"], name="ix_chat_identity_expiry"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        ("guest_token_hash__isnull", True),
                        ("identity_type", "MEMBER"),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        ("guest_token_hash__isnull", False),
                        ("identity_type", "GUEST"),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_chat_identity_owner_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatattachment",
            constraint=models.UniqueConstraint(
                fields=("message", "sha256"), name="uq_chat_attachment_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["identity", "deleted_at", "-updated_at"],
                name="ix_chat_session_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["WARDROBE_BASED", "NEW_ITEM"])),
                name="ck_chat_session_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"), name="uq_chat_message_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id__isnull", False)),
                fields=("session", "client_message_id"),
                name="uq_chat_message_client_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="ck_chat_message_sequence",
            ),
        ),
    ]
