# Generated by Django 5.2.16 on 2026-08-11

import uuid

import django.db.models.deletion
from django.db import migrations, models


def seed_personas(apps, schema_editor):
    ChatSession = apps.get_model("chat", "ChatSession")
    PersonaProfile = apps.get_model("chat", "PersonaProfile")

    legacy_ids = ChatSession.objects.exclude(
        persona_profile_id__isnull=True
    ).values_list("persona_profile_id", flat=True)
    for persona_id in set(legacy_ids):
        PersonaProfile.objects.get_or_create(
            id=persona_id,
            defaults={
                "code": f"legacy-{persona_id.hex}",
                "name": "이전 페르소나",
                "prompt_config": {},
                "version": 1,
                "is_active": False,
            },
        )

    PersonaProfile.objects.get_or_create(
        code="default-stylist",
        defaults={
            "name": "AI 스타일리스트",
            "prompt_config": {
                "tone": "친절하고 근거 중심",
                "style_philosophy": (
                    "사용자 조건을 존중하고 실제 사용할 수 있는 아이템만 설명"
                ),
                "description_length": "medium",
            },
            "version": 1,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="summary_through_sequence",
            field=models.PositiveBigIntegerField(
                db_comment=(
                    "conversation_summary에 반영된 마지막 메시지 sequence (미요약이면 0)"
                ),
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="PersonaProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="페르소나 프로필 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="애플리케이션에서 참조하는 페르소나 고유 코드",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="사용자에게 표시할 스타일리스트 이름",
                        max_length=100,
                    ),
                ),
                (
                    "prompt_config",
                    models.JSONField(
                        blank=True,
                        db_comment=(
                            "말투·스타일 철학·설명 길이 등 페르소나 프롬프트 설정 JSON"
                        ),
                        default=dict,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        db_comment="프롬프트 변경 시 증가시키는 페르소나 버전 (1 이상)",
                        default=1,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="현재 기본 페르소나 여부 (전체에서 최대 1개)",
                        default=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="페르소나 생성 시각",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="페르소나 마지막 수정 시각",
                    ),
                ),
            ],
            options={
                "db_table": "persona_profile",
                "db_table_comment": (
                    "채팅 말투와 스타일 철학을 버전 관리하는 페르소나 프로필"
                ),
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="ck_persona_profile_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_persona_profile_active",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_personas, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE chat_session ADD CONSTRAINT "
                        "chat_session_persona_profile_id_fk "
                        "FOREIGN KEY (persona_profile_id) REFERENCES persona_profile(id) "
                        "DEFERRABLE INITIALLY DEFERRED; "
                        "CREATE INDEX ix_chat_session_persona "
                        "ON chat_session (persona_profile_id); "
                        "COMMENT ON COLUMN chat_session.persona_profile_id IS "
                        "'세션에 적용할 페르소나 프로필 FK (미지정이면 활성 기본값)';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE chat_session DROP CONSTRAINT "
                        "IF EXISTS chat_session_persona_profile_id_fk; "
                        "DROP INDEX IF EXISTS ix_chat_session_persona; "
                        "COMMENT ON COLUMN chat_session.persona_profile_id IS "
                        "'세션에 적용할 페르소나 프로필 UUID (미지정이면 활성 기본값)';"
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="chatsession",
                    name="persona_profile_id",
                ),
                migrations.AddField(
                    model_name="chatsession",
                    name="persona_profile",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="persona_profile_id",
                        db_comment=(
                            "세션에 적용할 페르소나 프로필 FK (미지정이면 활성 기본값)"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="chat.personaprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="채팅 실행 UUID (큐·추천 결과·SSE의 공통 추적 ID)",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "처리 대기"),
                            ("RUNNING", "처리 중"),
                            ("NEEDS_CLARIFICATION", "추가 질문"),
                            ("SUCCEEDED", "성공"),
                            ("FAILED", "실패"),
                        ],
                        db_comment=(
                            "실행 상태 (PENDING/RUNNING/NEEDS_CLARIFICATION/"
                            "SUCCEEDED/FAILED)"
                        ),
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "context_fingerprint",
                    models.CharField(
                        blank=True,
                        db_comment=(
                            "요청·프로필·옷장·날씨·인덱스·세션 조건 기반 SHA-256 지문"
                        ),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "context_cache_hit",
                    models.BooleanField(
                        db_comment="Redis 기본 컨텍스트 캐시 적중 여부",
                        default=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_comment="텍스트 LLM 제공자 코드 (기본 openai)",
                        default="openai",
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        db_comment="실행에 사용한 텍스트 LLM 모델명",
                        default="",
                        max_length=128,
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True,
                        db_comment="실행에 사용한 오케스트레이터 프롬프트 버전",
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "provider_response_id",
                    models.CharField(
                        blank=True,
                        db_comment="마지막 OpenAI Responses API 응답 ID",
                        default="",
                        max_length=128,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        db_comment="실행 전체 OpenAI 입력 토큰 수",
                        default=0,
                    ),
                ),
                (
                    "cached_input_tokens",
                    models.PositiveIntegerField(
                        db_comment="실행 전체 OpenAI 캐시 적중 입력 토큰 수",
                        default=0,
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        db_comment="실행 전체 OpenAI 출력 토큰 수",
                        default=0,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        db_comment="오케스트레이터 실행 전체 지연시간 (ms)",
                        default=0,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        db_comment="실패 오류 코드 (성공이면 빈 문자열)",
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        db_comment=(
                            "민감정보를 제거한 운영용 실패 요약 (성공이면 빈 문자열)"
                        ),
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="오케스트레이터 처리를 시작한 시각",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="성공·추가질문·실패로 처리가 종료된 시각",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="채팅 실행 생성 시각",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="채팅 실행 마지막 수정 시각",
                    ),
                ),
                (
                    "request_message",
                    models.OneToOneField(
                        db_comment=(
                            "실행을 시작한 사용자 메시지 FK (메시지당 실행 최대 1개)"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "response_message",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "실행이 생성한 최종 AI 메시지 FK (미완료이면 NULL)"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_runs",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_comment="실행이 속한 채팅 세션 FK (chat_session.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_run",
                "db_table_comment": (
                    "사용자 메시지별 채팅 오케스트레이터 실행·LLM·캐시·오류 추적"
                ),
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "status", "-created_at"],
                        name="ix_chat_run_session_status",
                    ),
                    models.Index(
                        fields=["context_fingerprint"],
                        name="ix_chat_run_context_fp",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "PENDING",
                                    "RUNNING",
                                    "NEEDS_CLARIFICATION",
                                    "SUCCEEDED",
                                    "FAILED",
                                ],
                            )
                        ),
                        name="ck_chat_run_status",
                    )
                ],
            },
        ),
    ]
