# Generated by Django 5.2.16 on 2026-08-14

from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chat_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="response_mode",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "기본 응답"),
                    ("STYLIST", "선택형 스타일리스트 응답"),
                ],
                db_comment=(
                    "현재 응답 모드 (DEFAULT/STYLIST, 기존 추천 mode와 별도)"
                ),
                default="DEFAULT",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="selected_persona_ids",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "현재 선택한 스타일리스트 ID JSON 배열 "
                    "(minimal/experimental/practical, 고정 순서, 최대 3개)"
                ),
                default=list,
                validators=[apps.chat.models.validate_selected_persona_ids],
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="persona_selection_updated_at",
            field=models.DateTimeField(
                blank=True,
                db_comment=(
                    "스타일리스트 선택 배열이 마지막으로 변경된 시각 "
                    "(미선택이면 NULL)"
                ),
                null=True,
            ),
        ),
        migrations.AlterModelTableComment(
            name="chatsession",
            table_comment=(
                "추천·응답 모드와 스타일리스트 선택·조건·대화 요약을 "
                "보관하는 채팅 세션"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.CheckConstraint(
                condition=models.Q(response_mode__in=["DEFAULT", "STYLIST"]),
                name="ck_chat_session_response_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(response_mode="DEFAULT")
                    | ~models.Q(selected_persona_ids=[])
                ),
                name="ck_chat_session_stylist_ids",
            ),
        ),
    ]
