# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chat_session_response_mode"),
        ("users", "0017_merge_email_auth_body_ratio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStylistSelection",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_comment=(
                            "마지막 스타일리스트 선택을 저장한 회원 FK "
                            "(users.id, 회원당 1행)"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stylist_selection",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_selected_persona_ids",
                    models.JSONField(
                        blank=True,
                        db_comment=(
                            "회원이 마지막으로 선택한 스타일리스트 ID JSON 배열 "
                            "(minimal/experimental/practical, 고정 순서, 1~3개)"
                        ),
                        validators=[
                            apps.chat.models.validate_member_last_selected_persona_ids
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="회원 스타일리스트 선택값 최초 생성 시각",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="회원 스타일리스트 선택값 마지막 변경 시각",
                    ),
                ),
            ],
            options={
                "db_table": "member_stylist_selection",
                "db_table_comment": "회원별 마지막 선택형 스타일리스트 ID와 변경 시각",
                "constraints": [
                    models.CheckConstraint(
                        condition=~models.Q(last_selected_persona_ids=[]),
                        name="ck_member_stylist_ids_not_empty",
                    ),
                ],
            },
        ),
    ]
