# Generated by Django 5.2.16 on 2026-08-14

from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_member_stylist_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatrun",
            name="response_mode",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "기본 응답"),
                    ("STYLIST", "선택형 스타일리스트 응답"),
                ],
                db_comment="실행 접수 당시 응답 모드 스냅샷 (DEFAULT/STYLIST)",
                default="DEFAULT",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="chatrun",
            name="persona_ids",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "실행 접수 당시 선택 스타일리스트 ID JSON 배열 "
                    "(고정 순서, 선택하지 않았으면 빈 배열)"
                ),
                default=list,
                validators=[apps.chat.models.validate_selected_persona_ids],
            ),
        ),
        migrations.AddField(
            model_name="chatrun",
            name="persona_versions",
            field=models.JSONField(
                blank=True,
                db_comment="실행 접수 당시 스타일리스트 ID별 설정 버전 JSON 객체",
                default=dict,
                validators=[apps.chat.models.validate_persona_version_snapshot],
            ),
        ),
        migrations.AddField(
            model_name="chatrun",
            name="persona_prompt_versions",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "실행 접수 당시 스타일리스트 ID별 프롬프트 버전 JSON 객체"
                ),
                default=dict,
                validators=[
                    apps.chat.models.validate_persona_prompt_version_snapshot
                ],
            ),
        ),
        migrations.AddField(
            model_name="chatrun",
            name="stylist_config_version",
            field=models.CharField(
                blank=True,
                db_comment="실행 접수 당시 스타일리스트 설정 파일 스키마 버전",
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterModelTableComment(
            name="chatrun",
            table_comment=(
                "사용자 메시지별 응답 상태 스냅샷과 오케스트레이터·LLM·오류 추적"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatrun",
            constraint=models.CheckConstraint(
                condition=models.Q(response_mode__in=["DEFAULT", "STYLIST"]),
                name="ck_chat_run_response_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(response_mode="DEFAULT") | ~models.Q(persona_ids=[])
                ),
                name="ck_chat_run_stylist_ids",
            ),
        ),
    ]
