# Generated by Django 5.2.16 on 2026-08-14

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_chat_run_response_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRunPersona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="스타일리스트별 채팅 실행 UUID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "persona_id",
                    models.CharField(
                        db_comment=(
                            "실행할 스타일리스트 고정 ID "
                            "(minimal/experimental/practical)"
                        ),
                        max_length=32,
                        validators=[apps.chat.models.validate_stylist_persona_id],
                    ),
                ),
                (
                    "persona_version",
                    models.PositiveIntegerField(
                        db_comment=(
                            "ChatRun에 고정된 스타일리스트 설정 버전 (1 이상)"
                        )
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        db_comment=(
                            "ChatRun에 고정된 스타일리스트 프롬프트 버전"
                        ),
                        max_length=64,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        db_comment=(
                            "스타일리스트 고정 표시 순서 "
                            "(minimal=1/experimental=2/practical=3)"
                        )
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "처리 대기"),
                            ("RUNNING", "처리 중"),
                            ("SUCCEEDED", "성공"),
                            ("FAILED", "실패"),
                        ],
                        db_comment=(
                            "스타일리스트별 실행 상태 "
                            "(PENDING/RUNNING/SUCCEEDED/FAILED)"
                        ),
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        db_comment="스타일리스트별 추천 실행 지연시간 (ms)",
                        default=0,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        db_comment=(
                            "스타일리스트 실행 실패 오류 코드 "
                            "(실패가 아니면 빈 문자열)"
                        ),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        db_comment=(
                            "민감정보를 제거한 스타일리스트 실행 실패 요약"
                        ),
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "strategy_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment=(
                            "실행 접수 당시 스타일리스트 추천 전략 설정 JSON 스냅샷"
                        ),
                        default=dict,
                    ),
                ),
                (
                    "hypothesis_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="실험형 검색 가설과 fallback 판단 JSON 스냅샷",
                        default=dict,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        db_comment=(
                            "해당 스타일리스트 실행 재시도 횟수 (최초 실행은 0)"
                        ),
                        default=0,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="스타일리스트별 추천 처리를 시작한 시각",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment=(
                            "스타일리스트별 추천 처리가 성공 또는 실패로 종료된 시각"
                        ),
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="스타일리스트별 실행 상태 행 생성 시각",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="스타일리스트별 실행 상태 마지막 변경 시각",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_comment="상위 채팅 실행 FK (chat_run.id)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_executions",
                        to="chat.chatrun",
                    ),
                ),
            ],
            options={
                "db_table": "chat_run_persona",
                "db_table_comment": (
                    "채팅 실행에 속한 스타일리스트별 독립 추천 상태와 오류·전략"
                ),
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["run", "status"],
                        name="ix_chat_run_persona_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "persona_id"),
                        name="uq_chat_run_persona_id",
                    ),
                    models.UniqueConstraint(
                        fields=("run", "display_order"),
                        name="uq_chat_run_persona_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=[
                                "PENDING",
                                "RUNNING",
                                "SUCCEEDED",
                                "FAILED",
                            ]
                        ),
                        name="ck_chat_run_persona_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(persona_version__gte=1),
                        name="ck_chat_run_persona_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            display_order__gte=1,
                            display_order__lte=3,
                        ),
                        name="ck_chat_run_persona_order",
                    ),
                ],
            },
        ),
    ]
