# Generated by Django 5.2.16 on 2026-08-16 09:46

from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012 - Django migration contract
        ("chat", "0011_chatrunpersona_alternative_state"),
    ]

    operations = [  # noqa: RUF012 - Django migration contract
        migrations.AddField(
            model_name="chatrun",
            name="personalization_snapshot",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "실행 접수 당시 개인화 원천별 행 수·마지막 변경 시각·설정 "
                    "지문 JSON (기존 실행은 빈 객체)"
                ),
                default=dict,
                validators=[apps.chat.models.validate_personalization_snapshot],
            ),
        ),
    ]
