# Generated by Django 5.2 on 2026-08-17

from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012 - Django migration contract
        ("chat", "0012_chatrun_personalization_snapshot"),
    ]

    operations = [  # noqa: RUF012 - Django migration contract
        migrations.AddField(
            model_name="chatrun",
            name="reference_snapshot",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "실행 접수 당시 공유 옷장 참조 아이템·이미지·태그·벡터 위치 "
                    "JSON (참조가 없거나 기존 실행이면 빈 객체, 원본 벡터는 저장하지 않음)"
                ),
                default=dict,
                validators=[apps.chat.models.validate_reference_snapshot],
            ),
        ),
    ]
