# Generated by Django 5.2.16 on 2026-08-18 11:28

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatrun_reference_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='wardrobe_scope_snapshot',
            field=models.JSONField(blank=True, db_comment='실행 접수 당시 개인 옷장 기본 카테고리·해시태그 범위와 후보 아이템 JSON (범위가 없거나 기존 실행이면 빈 객체)', default=dict, validators=[apps.chat.models.validate_wardrobe_scope_snapshot]),
        ),
    ]
