# Generated by Django 5.2.16 on 2026-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_wardrobe_scope_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='degradation',
            field=models.JSONField(blank=True, db_comment='응답 품질 저하 기록 JSON (설명 LLM 실패로 규칙 문구를 쓴 경우의 여부·사유 등, 운영 관측용이며 사용자에게 노출하지 않음)', default=dict),
        ),
    ]
